// 25 additional seed breakfasts — varied cuisines and macro profiles
// (high-protein, low-carb, high-carb, low-fat, high-fat, balanced).

import type { Recipe } from "./meal-data";

export const BREAKFAST_RECIPES_2: Recipe[] = [
  {
    id: "greek-yogurt-power-bowl",
    title: "Greek Yogurt Power Bowl",
    cuisine: "Greek",
    mealType: ["breakfast"],
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    macros: { calories: 380, protein: 32, carbs: 38, fat: 11 },
    tags: ["high-protein", "no-cook", "quick", "vegetarian", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "nonfat Greek yogurt", perishable: true, shelfDays: 10 },
      { amount: "½ cup", item: "fresh blueberries", perishable: true, shelfDays: 5 },
      { amount: "1 tbsp", item: "honey" },
      { amount: "2 tbsp", item: "sliced almonds" },
      { amount: "1 tbsp", item: "chia seeds" },
      { amount: "¼ tsp", item: "cinnamon" },
    ],
    steps: [
      "Spoon yogurt into a bowl.",
      "Top with blueberries, almonds, and chia seeds.",
      "Drizzle honey and dust with cinnamon.",
    ],
  },
  {
    id: "shakshuka-feta",
    title: "Shakshuka with Feta",
    cuisine: "Middle Eastern",
    mealType: ["breakfast"],
    cookTime: 20,
    prepTime: 10,
    servings: 2,
    macros: { calories: 340, protein: 19, carbs: 18, fat: 22 },
    tags: ["vegetarian", "low-carb", "gluten-free", "spicy"],
    source: "seed",
    ingredients: [
      { amount: "4", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "1 can (14 oz)", item: "crushed tomatoes" },
      { amount: "1", item: "red bell pepper, diced", perishable: true, shelfDays: 7 },
      { amount: "½", item: "yellow onion, diced", perishable: true, shelfDays: 14 },
      { amount: "3 oz", item: "feta cheese, crumbled", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "olive oil" },
      { amount: "1 tsp", item: "smoked paprika" },
      { amount: "1 tsp", item: "cumin" },
    ],
    steps: [
      "Sauté onion and pepper in olive oil until soft, 6 min.",
      "Add spices, then crushed tomatoes. Simmer 8 min until thick.",
      "Make 4 wells and crack in the eggs. Cover and cook 5–6 min until whites set.",
      "Scatter feta over the top and serve from the pan.",
    ],
  },
  {
    id: "banana-oat-protein-smoothie-bowl",
    title: "Banana Oat Protein Smoothie Bowl",
    cuisine: "American",
    mealType: ["breakfast"],
    cookTime: 0,
    prepTime: 7,
    servings: 1,
    macros: { calories: 470, protein: 35, carbs: 62, fat: 9 },
    tags: ["high-protein", "high-carb", "no-cook", "quick", "vegetarian"],
    source: "seed",
    ingredients: [
      { amount: "1", item: "frozen banana" },
      { amount: "1 scoop", item: "vanilla protein powder" },
      { amount: "½ cup", item: "rolled oats" },
      { amount: "¾ cup", item: "milk", perishable: true, shelfDays: 7 },
      { amount: "½ cup", item: "sliced strawberries", perishable: true, shelfDays: 4 },
      { amount: "1 tbsp", item: "granola" },
    ],
    steps: [
      "Blend banana, protein powder, oats, and milk until thick and smooth.",
      "Pour into a bowl.",
      "Top with strawberries and granola.",
    ],
  },
  {
    id: "keto-avocado-egg-plate",
    title: "Keto Avocado & Bacon Egg Plate",
    cuisine: "American",
    mealType: ["breakfast"],
    cookTime: 12,
    prepTime: 5,
    servings: 1,
    macros: { calories: 540, protein: 24, carbs: 9, fat: 46 },
    tags: ["keto", "low-carb", "high-fat", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "3", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "3 slices", item: "bacon", perishable: true, shelfDays: 7 },
      { amount: "1", item: "avocado, sliced", perishable: true, shelfDays: 3 },
      { amount: "1 tbsp", item: "butter" },
      { amount: "1 handful", item: "arugula", perishable: true, shelfDays: 4 },
      { amount: "1 tsp", item: "everything bagel seasoning" },
    ],
    steps: [
      "Cook bacon in a skillet until crisp. Set aside.",
      "Fry eggs in butter to your liking.",
      "Plate eggs and bacon with sliced avocado over arugula.",
      "Sprinkle avocado with everything seasoning.",
    ],
  },
  {
    id: "japanese-tamago-rice-bowl",
    title: "Japanese Tamago Kake Gohan Bowl",
    cuisine: "Japanese",
    mealType: ["breakfast"],
    cookTime: 15,
    prepTime: 5,
    servings: 1,
    macros: { calories: 420, protein: 18, carbs: 64, fat: 10 },
    tags: ["high-carb", "low-fat", "quick"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "cooked short-grain rice" },
      { amount: "2", item: "very fresh eggs", perishable: true, shelfDays: 21 },
      { amount: "1 tbsp", item: "soy sauce (low sodium)" },
      { amount: "1 tsp", item: "sesame oil" },
      { amount: "1", item: "scallion, thinly sliced", perishable: true, shelfDays: 7 },
      { amount: "1 sheet", item: "nori, crumbled" },
      { amount: "1 tsp", item: "sesame seeds" },
    ],
    steps: [
      "Heat rice until steaming hot (fresh or microwaved).",
      "Soft-scramble the eggs gently in sesame oil, keeping them custardy.",
      "Pile eggs over the rice and season with soy sauce.",
      "Top with scallion, nori, and sesame seeds.",
    ],
  },
  {
    id: "berry-quinoa-breakfast-bowl",
    title: "Warm Berry Quinoa Breakfast Bowl",
    cuisine: "American",
    mealType: ["breakfast"],
    cookTime: 18,
    prepTime: 5,
    servings: 2,
    macros: { calories: 390, protein: 12, carbs: 68, fat: 8 },
    tags: ["vegan", "high-carb", "low-fat", "gluten-free", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "quinoa, rinsed" },
      { amount: "2 cups", item: "almond milk" },
      { amount: "1 cup", item: "mixed berries", perishable: true, shelfDays: 4 },
      { amount: "2 tbsp", item: "maple syrup" },
      { amount: "½ tsp", item: "cinnamon" },
      { amount: "1 tsp", item: "vanilla extract" },
    ],
    steps: [
      "Simmer quinoa in almond milk with cinnamon 15 min until tender and creamy.",
      "Stir in vanilla and maple syrup.",
      "Spoon into bowls and pile berries on top.",
    ],
  },
  {
    id: "smoked-turkey-egg-white-wrap",
    title: "Smoked Turkey & Egg White Wrap",
    cuisine: "American",
    mealType: ["breakfast"],
    cookTime: 8,
    prepTime: 5,
    servings: 1,
    macros: { calories: 350, protein: 38, carbs: 32, fat: 8 },
    tags: ["high-protein", "low-fat", "quick"],
    source: "seed",
    ingredients: [
      { amount: "¾ cup", item: "liquid egg whites", perishable: true, shelfDays: 7 },
      { amount: "3 oz", item: "smoked turkey breast, sliced", perishable: true, shelfDays: 5 },
      { amount: "1 large", item: "whole wheat tortilla" },
      { amount: "1 handful", item: "baby spinach", perishable: true, shelfDays: 5 },
      { amount: "2 tbsp", item: "salsa" },
      { amount: "1 slice", item: "reduced-fat provolone", perishable: true, shelfDays: 14 },
    ],
    steps: [
      "Scramble egg whites in a non-stick pan until just set.",
      "Warm the tortilla. Layer spinach, turkey, eggs, and provolone.",
      "Spoon over salsa, fold in the sides, and roll tightly.",
      "Toast the wrap seam-side down 1 min to seal.",
    ],
  },
  {
    id: "french-toast-brioche-light",
    title: "Cinnamon French Toast with Yogurt Cream",
    cuisine: "French",
    mealType: ["breakfast"],
    cookTime: 12,
    prepTime: 8,
    servings: 2,
    macros: { calories: 450, protein: 20, carbs: 60, fat: 14 },
    tags: ["high-carb", "vegetarian", "sweet"],
    source: "seed",
    ingredients: [
      { amount: "4 slices", item: "brioche or challah bread" },
      { amount: "2", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "½ cup", item: "milk", perishable: true, shelfDays: 7 },
      { amount: "1 tsp", item: "cinnamon" },
      { amount: "1 tsp", item: "vanilla extract" },
      { amount: "½ cup", item: "Greek yogurt", perishable: true, shelfDays: 10 },
      { amount: "1 tbsp", item: "honey" },
      { amount: "1 tbsp", item: "butter" },
    ],
    steps: [
      "Whisk eggs, milk, cinnamon, and vanilla in a shallow dish.",
      "Soak bread slices 20 seconds per side.",
      "Cook in butter over medium 2–3 min per side until golden.",
      "Whip yogurt with honey and dollop over the warm toast.",
    ],
  },
  {
    id: "huevos-rancheros-light",
    title: "Huevos Rancheros with Black Beans",
    cuisine: "Mexican",
    mealType: ["breakfast"],
    cookTime: 15,
    prepTime: 8,
    servings: 2,
    macros: { calories: 430, protein: 22, carbs: 46, fat: 18 },
    tags: ["vegetarian", "balanced", "gluten-free", "spicy"],
    source: "seed",
    ingredients: [
      { amount: "4", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "4", item: "corn tortillas" },
      { amount: "1 cup", item: "canned black beans, drained" },
      { amount: "¾ cup", item: "red salsa" },
      { amount: "¼ cup", item: "cotija or feta, crumbled", perishable: true, shelfDays: 14 },
      { amount: "1", item: "avocado, sliced", perishable: true, shelfDays: 3 },
      { amount: "2 tbsp", item: "cilantro, chopped", perishable: true, shelfDays: 5 },
      { amount: "1 tbsp", item: "olive oil" },
    ],
    steps: [
      "Warm black beans with a spoonful of salsa in a small pot.",
      "Char tortillas directly over a flame or in a dry skillet.",
      "Fry eggs in olive oil sunny-side up.",
      "Stack: tortilla → beans → egg → salsa. Finish with cotija, avocado, and cilantro.",
    ],
  },
  {
    id: "overnight-oats-pb-banana",
    title: "Peanut Butter Banana Overnight Oats",
    cuisine: "American",
    mealType: ["breakfast"],
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    macros: { calories: 520, protein: 22, carbs: 64, fat: 20 },
    tags: ["vegetarian", "meal-prep", "no-cook", "high-carb"],
    source: "seed",
    ingredients: [
      { amount: "½ cup", item: "rolled oats" },
      { amount: "¾ cup", item: "milk", perishable: true, shelfDays: 7 },
      { amount: "2 tbsp", item: "peanut butter" },
      { amount: "1", item: "banana, sliced" },
      { amount: "1 tbsp", item: "chia seeds" },
      { amount: "1 tsp", item: "honey" },
    ],
    steps: [
      "Stir oats, milk, chia, honey, and half the peanut butter in a jar.",
      "Refrigerate overnight (or at least 4 hours).",
      "Top with banana slices and the remaining peanut butter before eating.",
    ],
  },
  {
    id: "spinach-mushroom-egg-bites",
    title: "Spinach & Mushroom Egg Bites",
    cuisine: "American",
    mealType: ["breakfast"],
    cookTime: 22,
    prepTime: 10,
    servings: 4,
    macros: { calories: 210, protein: 18, carbs: 5, fat: 13 },
    tags: ["high-protein", "low-carb", "meal-prep", "vegetarian", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "8", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "1 cup", item: "baby spinach, chopped", perishable: true, shelfDays: 5 },
      { amount: "1 cup", item: "mushrooms, diced", perishable: true, shelfDays: 5 },
      { amount: "½ cup", item: "cottage cheese", perishable: true, shelfDays: 7 },
      { amount: "½ cup", item: "shredded cheddar", perishable: true, shelfDays: 14 },
      { amount: "¼ tsp", item: "black pepper" },
    ],
    steps: [
      "Preheat oven to 350°F. Grease a 12-cup muffin tin.",
      "Sauté mushrooms until browned; wilt in spinach.",
      "Blend eggs and cottage cheese until smooth. Stir in veggies and cheddar.",
      "Fill cups ¾ full. Bake 18–20 min until just set.",
      "Cool 5 min — keeps refrigerated 4 days.",
    ],
  },
  {
    id: "congee-ginger-chicken",
    title: "Ginger Chicken Congee",
    cuisine: "Chinese",
    mealType: ["breakfast"],
    cookTime: 40,
    prepTime: 10,
    servings: 3,
    macros: { calories: 320, protein: 26, carbs: 42, fat: 5 },
    tags: ["low-fat", "high-protein", "comfort", "gluten-free", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "¾ cup", item: "jasmine rice" },
      { amount: "6 cups", item: "chicken broth" },
      { amount: "2", item: "chicken breasts", perishable: true, shelfDays: 2 },
      { amount: "2 inch", item: "fresh ginger, julienned", perishable: true, shelfDays: 21 },
      { amount: "2", item: "scallions, sliced", perishable: true, shelfDays: 7 },
      { amount: "1 tbsp", item: "soy sauce (low sodium)" },
      { amount: "1 tsp", item: "white pepper" },
    ],
    steps: [
      "Simmer rice, broth, and half the ginger 30 min, stirring occasionally, until porridge-thick.",
      "Add chicken breasts for the last 15 min; remove and shred.",
      "Stir shredded chicken back in with soy sauce and white pepper.",
      "Serve topped with scallions and the remaining fresh ginger.",
    ],
  },
  {
    id: "acai-bowl-classic",
    title: "Açaí Bowl with Granola",
    cuisine: "Brazilian",
    mealType: ["breakfast"],
    cookTime: 0,
    prepTime: 8,
    servings: 1,
    macros: { calories: 480, protein: 10, carbs: 76, fat: 17 },
    tags: ["vegan", "high-carb", "no-cook", "sweet"],
    source: "seed",
    ingredients: [
      { amount: "1 packet (100g)", item: "frozen açaí purée" },
      { amount: "1", item: "frozen banana" },
      { amount: "¼ cup", item: "almond milk" },
      { amount: "⅓ cup", item: "granola" },
      { amount: "½ cup", item: "sliced strawberries", perishable: true, shelfDays: 4 },
      { amount: "1 tbsp", item: "almond butter" },
      { amount: "1 tsp", item: "coconut flakes" },
    ],
    steps: [
      "Blend açaí, banana, and almond milk until thick — barely pourable.",
      "Scrape into a bowl.",
      "Arrange granola, strawberries, almond butter drizzle, and coconut on top.",
    ],
  },
  {
    id: "steak-eggs-low-carb",
    title: "Steak & Eggs with Chimichurri",
    cuisine: "Argentinian",
    mealType: ["breakfast"],
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    macros: { calories: 520, protein: 44, carbs: 6, fat: 36 },
    tags: ["high-protein", "low-carb", "keto", "high-fat", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "10 oz", item: "sirloin steak", perishable: true, shelfDays: 3 },
      { amount: "4", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "½ cup", item: "fresh parsley, minced", perishable: true, shelfDays: 5 },
      { amount: "2", item: "garlic cloves, minced" },
      { amount: "3 tbsp", item: "olive oil" },
      { amount: "1 tbsp", item: "red wine vinegar" },
      { amount: "½ tsp", item: "red pepper flakes" },
    ],
    steps: [
      "Chimichurri: stir parsley, garlic, olive oil, vinegar, and pepper flakes. Rest 10 min.",
      "Sear steak in a hot skillet 3–4 min per side for medium-rare. Rest 5 min.",
      "Fry eggs in the steak drippings.",
      "Slice steak against the grain, plate with eggs, and spoon over chimichurri.",
    ],
  },
  {
    id: "ricotta-toast-honey-pear",
    title: "Whipped Ricotta Toast with Pear & Honey",
    cuisine: "Italian",
    mealType: ["breakfast"],
    cookTime: 5,
    prepTime: 5,
    servings: 1,
    macros: { calories: 410, protein: 16, carbs: 52, fat: 16 },
    tags: ["vegetarian", "quick", "sweet", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "2 slices", item: "sourdough bread" },
      { amount: "½ cup", item: "ricotta", perishable: true, shelfDays: 7 },
      { amount: "1", item: "ripe pear, thinly sliced", perishable: true, shelfDays: 5 },
      { amount: "1 tbsp", item: "honey" },
      { amount: "2 tbsp", item: "chopped walnuts" },
      { amount: "1 pinch", item: "flaky sea salt" },
    ],
    steps: [
      "Toast sourdough until deeply golden.",
      "Whip ricotta with a fork until creamy; spread thick.",
      "Fan pear slices on top, scatter walnuts.",
      "Finish with honey and flaky salt.",
    ],
  },
  {
    id: "masala-omelette",
    title: "Masala Omelette with Toast",
    cuisine: "Indian",
    mealType: ["breakfast"],
    cookTime: 8,
    prepTime: 7,
    servings: 1,
    macros: { calories: 380, protein: 23, carbs: 28, fat: 19 },
    tags: ["vegetarian", "quick", "spicy", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "3", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "½", item: "small red onion, finely diced", perishable: true, shelfDays: 14 },
      { amount: "1", item: "green chili, minced", perishable: true, shelfDays: 7 },
      { amount: "1", item: "Roma tomato, diced", perishable: true, shelfDays: 4 },
      { amount: "2 tbsp", item: "cilantro, chopped", perishable: true, shelfDays: 5 },
      { amount: "½ tsp", item: "turmeric" },
      { amount: "½ tsp", item: "garam masala" },
      { amount: "2 slices", item: "whole wheat bread, toasted" },
      { amount: "1 tbsp", item: "ghee or butter" },
    ],
    steps: [
      "Whisk eggs with onion, chili, tomato, cilantro, and spices.",
      "Heat ghee in a non-stick skillet over medium.",
      "Pour in eggs; cook 2–3 min, fold, and cook 1 min more.",
      "Serve with hot buttered toast.",
    ],
  },
  {
    id: "smoothie-green-protein",
    title: "Green Protein Smoothie",
    cuisine: "American",
    mealType: ["breakfast"],
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    macros: { calories: 340, protein: 30, carbs: 40, fat: 7 },
    tags: ["high-protein", "low-fat", "no-cook", "quick", "vegetarian"],
    source: "seed",
    ingredients: [
      { amount: "1 scoop", item: "vanilla protein powder" },
      { amount: "2 cups", item: "baby spinach", perishable: true, shelfDays: 5 },
      { amount: "1", item: "frozen banana" },
      { amount: "½ cup", item: "frozen pineapple chunks" },
      { amount: "1 cup", item: "unsweetened almond milk" },
      { amount: "1 tbsp", item: "ground flaxseed" },
    ],
    steps: [
      "Add almond milk and spinach to the blender first; blitz smooth.",
      "Add banana, pineapple, protein powder, and flax.",
      "Blend until completely smooth and pour into a tall glass.",
    ],
  },
  {
    id: "croque-madame-light",
    title: "Croque Madame",
    cuisine: "French",
    mealType: ["breakfast"],
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    macros: { calories: 560, protein: 33, carbs: 38, fat: 30 },
    tags: ["high-fat", "high-protein", "indulgent"],
    source: "seed",
    ingredients: [
      { amount: "4 slices", item: "country white bread" },
      { amount: "6 oz", item: "ham, sliced", perishable: true, shelfDays: 5 },
      { amount: "1 cup", item: "shredded Gruyère", perishable: true, shelfDays: 14 },
      { amount: "2", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "1 cup", item: "milk", perishable: true, shelfDays: 7 },
      { amount: "2 tbsp", item: "butter" },
      { amount: "2 tbsp", item: "flour" },
      { amount: "1 pinch", item: "nutmeg" },
      { amount: "1 tsp", item: "Dijon mustard" },
    ],
    steps: [
      "Béchamel: melt butter, whisk in flour 1 min, then milk. Simmer until thick; season with nutmeg.",
      "Spread bread with Dijon. Layer ham and half the Gruyère; close sandwiches.",
      "Top each with béchamel and remaining cheese. Broil 4–5 min until bubbling.",
      "Fry eggs sunny-side up and slide one onto each sandwich.",
    ],
  },
  {
    id: "breakfast-burrito-bowl",
    title: "Breakfast Burrito Bowl",
    cuisine: "Mexican",
    mealType: ["breakfast"],
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    macros: { calories: 490, protein: 30, carbs: 48, fat: 20 },
    tags: ["high-protein", "balanced", "meal-prep", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "4", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "6 oz", item: "ground turkey", perishable: true, shelfDays: 2 },
      { amount: "1 cup", item: "cooked brown rice" },
      { amount: "½ cup", item: "canned black beans, drained" },
      { amount: "½ cup", item: "pico de gallo", perishable: true, shelfDays: 4 },
      { amount: "½", item: "avocado, diced", perishable: true, shelfDays: 3 },
      { amount: "1 tsp", item: "taco seasoning" },
      { amount: "1 tbsp", item: "olive oil" },
    ],
    steps: [
      "Brown turkey with taco seasoning in olive oil, 6 min.",
      "Scramble eggs in the same pan.",
      "Build bowls: rice, beans, turkey, eggs.",
      "Top with pico de gallo and avocado.",
    ],
  },
  {
    id: "swedish-cardamom-porridge",
    title: "Cardamom Oat Porridge with Apples",
    cuisine: "Scandinavian",
    mealType: ["breakfast"],
    cookTime: 12,
    prepTime: 5,
    servings: 2,
    macros: { calories: 360, protein: 11, carbs: 60, fat: 9 },
    tags: ["vegetarian", "high-carb", "low-fat", "comfort"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "rolled oats" },
      { amount: "2 cups", item: "milk", perishable: true, shelfDays: 7 },
      { amount: "1", item: "apple, grated", perishable: true, shelfDays: 14 },
      { amount: "½ tsp", item: "ground cardamom" },
      { amount: "1 tbsp", item: "maple syrup" },
      { amount: "2 tbsp", item: "chopped hazelnuts" },
    ],
    steps: [
      "Simmer oats, milk, and cardamom 8–10 min, stirring, until creamy.",
      "Stir in half the grated apple and the maple syrup.",
      "Top bowls with remaining apple and hazelnuts.",
    ],
  },
  {
    id: "lox-scramble-low-carb",
    title: "Smoked Salmon Soft Scramble",
    cuisine: "Scandinavian",
    mealType: ["breakfast"],
    cookTime: 8,
    prepTime: 5,
    servings: 2,
    macros: { calories: 330, protein: 28, carbs: 4, fat: 23 },
    tags: ["high-protein", "low-carb", "keto", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "5", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "4 oz", item: "smoked salmon, torn", perishable: true, shelfDays: 5 },
      { amount: "2 tbsp", item: "crème fraîche", perishable: true, shelfDays: 10 },
      { amount: "1 tbsp", item: "butter" },
      { amount: "1 tbsp", item: "fresh dill, chopped", perishable: true, shelfDays: 5 },
      { amount: "1 tbsp", item: "chives, snipped", perishable: true, shelfDays: 7 },
    ],
    steps: [
      "Whisk eggs. Melt butter over low heat.",
      "Cook eggs slowly, stirring constantly, until barely set and creamy.",
      "Off heat, fold in crème fraîche and smoked salmon.",
      "Shower with dill and chives.",
    ],
  },
  {
    id: "vietnamese-banh-mi-omelette",
    title: "Bánh Mì-Style Omelette Baguette",
    cuisine: "Vietnamese",
    mealType: ["breakfast"],
    cookTime: 10,
    prepTime: 10,
    servings: 2,
    macros: { calories: 470, protein: 22, carbs: 54, fat: 18 },
    tags: ["balanced", "quick"],
    source: "seed",
    ingredients: [
      { amount: "4", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "1", item: "small baguette, split" },
      { amount: "½ cup", item: "pickled carrots and daikon" },
      { amount: "¼", item: "cucumber, sliced lengthwise", perishable: true, shelfDays: 7 },
      { amount: "¼ cup", item: "cilantro sprigs", perishable: true, shelfDays: 5 },
      { amount: "1 tbsp", item: "mayonnaise" },
      { amount: "1 tsp", item: "sriracha" },
      { amount: "1 tbsp", item: "soy sauce (low sodium)" },
    ],
    steps: [
      "Whisk eggs with soy sauce; cook a thin folded omelette.",
      "Toast the baguette; spread with mayo and sriracha.",
      "Tuck in the omelette, pickles, cucumber, and cilantro.",
    ],
  },
  {
    id: "cottage-cheese-bowl-savory",
    title: "Savory Cottage Cheese Bowl",
    cuisine: "Mediterranean",
    mealType: ["breakfast"],
    cookTime: 0,
    prepTime: 6,
    servings: 1,
    macros: { calories: 300, protein: 30, carbs: 16, fat: 13 },
    tags: ["high-protein", "low-carb", "no-cook", "vegetarian", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "cottage cheese", perishable: true, shelfDays: 7 },
      { amount: "½ cup", item: "cherry tomatoes, halved", perishable: true, shelfDays: 5 },
      { amount: "¼", item: "cucumber, diced", perishable: true, shelfDays: 7 },
      { amount: "6", item: "kalamata olives, halved" },
      { amount: "1 tbsp", item: "olive oil" },
      { amount: "1 tsp", item: "za'atar" },
    ],
    steps: [
      "Spoon cottage cheese into a wide bowl.",
      "Top with tomatoes, cucumber, and olives.",
      "Drizzle olive oil and dust with za'atar.",
    ],
  },
  {
    id: "sweet-potato-breakfast-skillet",
    title: "Sweet Potato Turkey Breakfast Skillet",
    cuisine: "American",
    mealType: ["breakfast"],
    cookTime: 20,
    prepTime: 10,
    servings: 2,
    macros: { calories: 410, protein: 32, carbs: 36, fat: 16 },
    tags: ["high-protein", "balanced", "gluten-free", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "8 oz", item: "ground turkey", perishable: true, shelfDays: 2 },
      { amount: "1 large", item: "sweet potato, diced small", perishable: true, shelfDays: 14 },
      { amount: "4", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "½", item: "red onion, diced", perishable: true, shelfDays: 14 },
      { amount: "1 tsp", item: "smoked paprika" },
      { amount: "2 tbsp", item: "olive oil" },
      { amount: "2 cups", item: "baby kale", perishable: true, shelfDays: 5 },
    ],
    steps: [
      "Cook sweet potato in olive oil over medium, covered, 8 min until tender.",
      "Add turkey, onion, and paprika; brown 6 min.",
      "Wilt in kale. Make 4 wells and crack in eggs.",
      "Cover and cook 4–5 min until whites set.",
    ],
  },
  {
    id: "turkish-simit-platter",
    title: "Turkish Breakfast Platter",
    cuisine: "Turkish",
    mealType: ["breakfast"],
    cookTime: 8,
    prepTime: 10,
    servings: 2,
    macros: { calories: 520, protein: 22, carbs: 50, fat: 27 },
    tags: ["vegetarian", "balanced", "no-cook-mostly"],
    source: "seed",
    ingredients: [
      { amount: "2", item: "simit or sesame bagels" },
      { amount: "4 oz", item: "feta cheese", perishable: true, shelfDays: 14 },
      { amount: "2", item: "soft-boiled eggs", perishable: true, shelfDays: 21 },
      { amount: "1", item: "tomato, sliced", perishable: true, shelfDays: 4 },
      { amount: "½", item: "cucumber, sliced", perishable: true, shelfDays: 7 },
      { amount: "10", item: "olives, mixed" },
      { amount: "2 tbsp", item: "honey" },
      { amount: "2 tbsp", item: "tahini" },
    ],
    steps: [
      "Soft-boil eggs 6½ minutes; halve.",
      "Arrange feta, tomato, cucumber, olives, and eggs on a platter.",
      "Swirl honey into tahini for dipping.",
      "Serve with warm simit.",
    ],
  },
];
