// 25 additional seed lunches — varied cuisines and macro profiles.

import type { Recipe } from "./meal-data";

export const LUNCH_RECIPES_2: Recipe[] = [
  {
    id: "chicken-shawarma-bowl",
    title: "Chicken Shawarma Bowl",
    cuisine: "Middle Eastern",
    mealType: ["lunch"],
    cookTime: 20,
    prepTime: 15,
    servings: 2,
    macros: { calories: 520, protein: 42, carbs: 44, fat: 19 },
    tags: ["high-protein", "balanced", "meal-prep", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "chicken thighs, boneless", perishable: true, shelfDays: 2 },
      { amount: "1 cup", item: "cooked basmati rice" },
      { amount: "1 tbsp", item: "shawarma spice blend" },
      { amount: "½ cup", item: "Greek yogurt", perishable: true, shelfDays: 10 },
      { amount: "1", item: "garlic clove, grated" },
      { amount: "1 cup", item: "chopped cucumber-tomato salad", perishable: true, shelfDays: 4 },
      { amount: "2 tbsp", item: "olive oil" },
      { amount: "½", item: "lemon, juiced" },
    ],
    steps: [
      "Toss chicken with shawarma spice and 1 tbsp olive oil; marinate 10 min.",
      "Sear chicken over medium-high 5–6 min per side; rest, then slice.",
      "Stir yogurt with garlic and lemon for a quick sauce.",
      "Build bowls: rice, chicken, salad, and yogurt sauce.",
    ],
  },
  {
    id: "tuna-white-bean-salad",
    title: "Tuscan Tuna & White Bean Salad",
    cuisine: "Italian",
    mealType: ["lunch"],
    cookTime: 0,
    prepTime: 10,
    servings: 2,
    macros: { calories: 410, protein: 34, carbs: 36, fat: 15 },
    tags: ["high-protein", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "2 cans (5 oz)", item: "tuna in olive oil, drained" },
      { amount: "1 can (15 oz)", item: "cannellini beans, rinsed" },
      { amount: "½", item: "red onion, thinly sliced", perishable: true, shelfDays: 14 },
      { amount: "1 cup", item: "cherry tomatoes, halved", perishable: true, shelfDays: 5 },
      { amount: "¼ cup", item: "fresh parsley, chopped", perishable: true, shelfDays: 5 },
      { amount: "2 tbsp", item: "olive oil" },
      { amount: "1 tbsp", item: "red wine vinegar" },
      { amount: "2 cups", item: "arugula", perishable: true, shelfDays: 4 },
    ],
    steps: [
      "Whisk olive oil and vinegar with salt and pepper.",
      "Toss beans, onion, tomatoes, and parsley with the dressing.",
      "Flake in tuna and fold gently.",
      "Serve over arugula.",
    ],
  },
  {
    id: "bibimbap-bowl",
    title: "Beef Bibimbap Bowl",
    cuisine: "Korean",
    mealType: ["lunch"],
    cookTime: 20,
    prepTime: 15,
    servings: 2,
    macros: { calories: 560, protein: 33, carbs: 62, fat: 20 },
    tags: ["balanced", "high-carb", "spicy"],
    source: "seed",
    ingredients: [
      { amount: "8 oz", item: "ground beef (90% lean)", perishable: true, shelfDays: 2 },
      { amount: "1½ cups", item: "cooked short-grain rice" },
      { amount: "1 cup", item: "spinach, blanched", perishable: true, shelfDays: 5 },
      { amount: "1", item: "carrot, julienned", perishable: true, shelfDays: 14 },
      { amount: "1 cup", item: "bean sprouts", perishable: true, shelfDays: 3 },
      { amount: "2", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "2 tbsp", item: "gochujang" },
      { amount: "1 tbsp", item: "sesame oil" },
      { amount: "2 tbsp", item: "soy sauce (low sodium)" },
    ],
    steps: [
      "Brown beef with soy sauce and half the sesame oil.",
      "Quickly sauté carrot; blanch spinach and sprouts; season each with a pinch of salt.",
      "Fry eggs sunny-side up.",
      "Arrange rice, beef, and vegetables in bowls. Top with egg, gochujang, and remaining sesame oil.",
    ],
  },
  {
    id: "greek-chicken-pita",
    title: "Greek Chicken Pita with Tzatziki",
    cuisine: "Greek",
    mealType: ["lunch"],
    cookTime: 12,
    prepTime: 12,
    servings: 2,
    macros: { calories: 480, protein: 40, carbs: 42, fat: 17 },
    tags: ["high-protein", "balanced", "quick"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "chicken breast, cubed", perishable: true, shelfDays: 2 },
      { amount: "2", item: "pita breads" },
      { amount: "½ cup", item: "Greek yogurt", perishable: true, shelfDays: 10 },
      { amount: "¼", item: "cucumber, grated", perishable: true, shelfDays: 7 },
      { amount: "1", item: "garlic clove, grated" },
      { amount: "1 tsp", item: "dried oregano" },
      { amount: "1 cup", item: "shredded lettuce", perishable: true, shelfDays: 4 },
      { amount: "½ cup", item: "cherry tomatoes, halved", perishable: true, shelfDays: 5 },
      { amount: "1 tbsp", item: "olive oil" },
    ],
    steps: [
      "Tzatziki: squeeze cucumber dry; stir into yogurt with garlic and a pinch of salt.",
      "Toss chicken with oregano, olive oil, salt, and pepper. Sear 6–8 min until cooked.",
      "Warm pitas.",
      "Stuff with lettuce, chicken, tomatoes, and plenty of tzatziki.",
    ],
  },
  {
    id: "soba-noodle-salad",
    title: "Sesame Soba Noodle Salad with Edamame",
    cuisine: "Japanese",
    mealType: ["lunch"],
    cookTime: 8,
    prepTime: 12,
    servings: 2,
    macros: { calories: 470, protein: 21, carbs: 68, fat: 14 },
    tags: ["vegan", "high-carb", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "6 oz", item: "soba noodles" },
      { amount: "1 cup", item: "shelled edamame, cooked" },
      { amount: "1", item: "carrot, ribboned", perishable: true, shelfDays: 14 },
      { amount: "1", item: "red bell pepper, sliced", perishable: true, shelfDays: 7 },
      { amount: "2", item: "scallions, sliced", perishable: true, shelfDays: 7 },
      { amount: "2 tbsp", item: "soy sauce (low sodium)" },
      { amount: "1 tbsp", item: "rice vinegar" },
      { amount: "1 tbsp", item: "sesame oil" },
      { amount: "1 tbsp", item: "sesame seeds" },
    ],
    steps: [
      "Cook soba per package; rinse under cold water.",
      "Whisk soy, vinegar, and sesame oil.",
      "Toss noodles with edamame, carrot, pepper, and dressing.",
      "Top with scallions and sesame seeds. Eat cold or room temp.",
    ],
  },
  {
    id: "turkey-avocado-club-wrap",
    title: "Turkey Avocado Club Wrap",
    cuisine: "American",
    mealType: ["lunch"],
    cookTime: 5,
    prepTime: 8,
    servings: 1,
    macros: { calories: 520, protein: 38, carbs: 40, fat: 23 },
    tags: ["high-protein", "quick", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "1 large", item: "whole wheat tortilla" },
      { amount: "5 oz", item: "roasted turkey breast, sliced", perishable: true, shelfDays: 5 },
      { amount: "2 slices", item: "bacon, cooked", perishable: true, shelfDays: 7 },
      { amount: "½", item: "avocado, mashed", perishable: true, shelfDays: 3 },
      { amount: "1", item: "Roma tomato, sliced", perishable: true, shelfDays: 4 },
      { amount: "1 cup", item: "shredded romaine", perishable: true, shelfDays: 4 },
      { amount: "1 tbsp", item: "light mayo" },
    ],
    steps: [
      "Spread tortilla with mashed avocado and mayo.",
      "Layer turkey, bacon, tomato, and romaine.",
      "Roll tightly, slice in half, and toast seam-side down 1 min.",
    ],
  },
  {
    id: "lentil-soup-lemon",
    title: "Lemony Red Lentil Soup",
    cuisine: "Middle Eastern",
    mealType: ["lunch"],
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    macros: { calories: 310, protein: 16, carbs: 48, fat: 7 },
    tags: ["vegan", "low-fat", "high-carb", "meal-prep", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1½ cups", item: "red lentils, rinsed" },
      { amount: "1", item: "yellow onion, diced", perishable: true, shelfDays: 14 },
      { amount: "2", item: "carrots, diced", perishable: true, shelfDays: 14 },
      { amount: "3", item: "garlic cloves, minced" },
      { amount: "1 tsp", item: "cumin" },
      { amount: "½ tsp", item: "turmeric" },
      { amount: "6 cups", item: "vegetable broth" },
      { amount: "1", item: "lemon, juiced" },
      { amount: "2 tbsp", item: "olive oil" },
    ],
    steps: [
      "Sweat onion and carrot in olive oil 5 min; add garlic and spices 1 min.",
      "Add lentils and broth. Simmer 20 min until lentils collapse.",
      "Blend half the soup for body (or all, for silky).",
      "Brighten with lemon juice; season and serve.",
    ],
  },
  {
    id: "banh-mi-chicken-bowl",
    title: "Vietnamese Chicken Rice Bowl",
    cuisine: "Vietnamese",
    mealType: ["lunch"],
    cookTime: 15,
    prepTime: 12,
    servings: 2,
    macros: { calories: 490, protein: 38, carbs: 56, fat: 12 },
    tags: ["high-protein", "low-fat", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "chicken breast, sliced thin", perishable: true, shelfDays: 2 },
      { amount: "1½ cups", item: "cooked jasmine rice" },
      { amount: "2 tbsp", item: "fish sauce" },
      { amount: "1 tbsp", item: "brown sugar" },
      { amount: "2", item: "garlic cloves, minced" },
      { amount: "1 cup", item: "pickled carrots and daikon" },
      { amount: "½", item: "cucumber, sliced", perishable: true, shelfDays: 7 },
      { amount: "¼ cup", item: "cilantro", perishable: true, shelfDays: 5 },
      { amount: "1", item: "lime, in wedges" },
    ],
    steps: [
      "Marinate chicken in fish sauce, sugar, and garlic 10 min.",
      "Sear over high heat 2–3 min per side until caramelized.",
      "Serve over rice with pickles, cucumber, and cilantro.",
      "Squeeze lime over everything.",
    ],
  },
  {
    id: "caprese-quinoa-salad",
    title: "Caprese Quinoa Salad",
    cuisine: "Italian",
    mealType: ["lunch"],
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    macros: { calories: 430, protein: 18, carbs: 46, fat: 20 },
    tags: ["vegetarian", "balanced", "meal-prep", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "quinoa, rinsed" },
      { amount: "8 oz", item: "fresh mozzarella pearls", perishable: true, shelfDays: 7 },
      { amount: "1½ cups", item: "cherry tomatoes, halved", perishable: true, shelfDays: 5 },
      { amount: "½ cup", item: "fresh basil, torn", perishable: true, shelfDays: 4 },
      { amount: "2 tbsp", item: "olive oil" },
      { amount: "1 tbsp", item: "balsamic glaze" },
    ],
    steps: [
      "Cook quinoa in salted water 15 min; cool slightly.",
      "Toss with tomatoes, mozzarella, basil, and olive oil.",
      "Season, then drizzle with balsamic glaze.",
    ],
  },
  {
    id: "thai-larb-lettuce-cups",
    title: "Thai Chicken Larb Lettuce Cups",
    cuisine: "Thai",
    mealType: ["lunch"],
    cookTime: 12,
    prepTime: 12,
    servings: 2,
    macros: { calories: 360, protein: 35, carbs: 14, fat: 18 },
    tags: ["high-protein", "low-carb", "spicy", "gluten-free", "quick"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "ground chicken", perishable: true, shelfDays: 2 },
      { amount: "1 head", item: "butter lettuce, leaves separated", perishable: true, shelfDays: 5 },
      { amount: "2 tbsp", item: "fish sauce" },
      { amount: "2", item: "limes, juiced" },
      { amount: "2", item: "shallots, thinly sliced", perishable: true, shelfDays: 14 },
      { amount: "½ cup", item: "fresh mint", perishable: true, shelfDays: 4 },
      { amount: "½ cup", item: "cilantro", perishable: true, shelfDays: 5 },
      { amount: "1 tbsp", item: "toasted rice powder" },
      { amount: "1 tsp", item: "chili flakes" },
    ],
    steps: [
      "Cook ground chicken in a dry skillet, breaking it up, until done.",
      "Off heat, toss with fish sauce, lime juice, shallots, and chili flakes.",
      "Fold in mint, cilantro, and toasted rice powder.",
      "Spoon into lettuce cups.",
    ],
  },
  {
    id: "salmon-poke-bowl",
    title: "Salmon Poke Bowl",
    cuisine: "Hawaiian",
    mealType: ["lunch"],
    cookTime: 0,
    prepTime: 15,
    servings: 2,
    macros: { calories: 510, protein: 34, carbs: 58, fat: 16 },
    tags: ["high-protein", "no-cook", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "12 oz", item: "sushi-grade salmon, cubed", perishable: true, shelfDays: 1 },
      { amount: "1½ cups", item: "cooked sushi rice" },
      { amount: "2 tbsp", item: "soy sauce (low sodium)" },
      { amount: "1 tbsp", item: "sesame oil" },
      { amount: "1", item: "avocado, diced", perishable: true, shelfDays: 3 },
      { amount: "½ cup", item: "shelled edamame, cooked" },
      { amount: "¼", item: "cucumber, diced", perishable: true, shelfDays: 7 },
      { amount: "1", item: "scallion, sliced", perishable: true, shelfDays: 7 },
      { amount: "1 tsp", item: "sesame seeds" },
    ],
    steps: [
      "Toss salmon with soy sauce and sesame oil; rest 5 min.",
      "Build bowls over warm rice: salmon, avocado, edamame, cucumber.",
      "Finish with scallion and sesame seeds.",
    ],
  },
  {
    id: "chipotle-black-bean-burrito",
    title: "Chipotle Black Bean Burrito",
    cuisine: "Mexican",
    mealType: ["lunch"],
    cookTime: 10,
    prepTime: 10,
    servings: 2,
    macros: { calories: 540, protein: 20, carbs: 78, fat: 17 },
    tags: ["vegetarian", "high-carb", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "2 large", item: "flour tortillas" },
      { amount: "1 can (15 oz)", item: "black beans, drained" },
      { amount: "1 cup", item: "cooked cilantro-lime rice" },
      { amount: "1", item: "chipotle in adobo, minced" },
      { amount: "½ cup", item: "shredded Monterey Jack", perishable: true, shelfDays: 14 },
      { amount: "½ cup", item: "pico de gallo", perishable: true, shelfDays: 4 },
      { amount: "¼ cup", item: "sour cream", perishable: true, shelfDays: 10 },
    ],
    steps: [
      "Warm beans with the minced chipotle and a splash of water; mash lightly.",
      "Layer tortillas with rice, beans, cheese, and pico.",
      "Roll into burritos, tucking the ends.",
      "Griddle seam-side down until crisp. Serve with sour cream.",
    ],
  },
  {
    id: "cobb-salad-classic",
    title: "Classic Cobb Salad",
    cuisine: "American",
    mealType: ["lunch"],
    cookTime: 12,
    prepTime: 15,
    servings: 2,
    macros: { calories: 480, protein: 40, carbs: 12, fat: 31 },
    tags: ["high-protein", "low-carb", "high-fat", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "2", item: "chicken breasts, grilled", perishable: true, shelfDays: 2 },
      { amount: "2", item: "hard-boiled eggs, quartered", perishable: true, shelfDays: 21 },
      { amount: "3 slices", item: "bacon, crumbled", perishable: true, shelfDays: 7 },
      { amount: "1 head", item: "romaine, chopped", perishable: true, shelfDays: 5 },
      { amount: "½", item: "avocado, diced", perishable: true, shelfDays: 3 },
      { amount: "¼ cup", item: "blue cheese, crumbled", perishable: true, shelfDays: 14 },
      { amount: "½ cup", item: "cherry tomatoes, halved", perishable: true, shelfDays: 5 },
      { amount: "2 tbsp", item: "red wine vinaigrette" },
    ],
    steps: [
      "Season and grill chicken 5–6 min per side; rest and slice.",
      "Arrange romaine in wide bowls.",
      "Lay chicken, eggs, bacon, avocado, tomatoes, and blue cheese in rows.",
      "Drizzle with vinaigrette just before eating.",
    ],
  },
  {
    id: "falafel-hummus-plate",
    title: "Falafel & Hummus Mezze Plate",
    cuisine: "Middle Eastern",
    mealType: ["lunch"],
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    macros: { calories: 520, protein: 18, carbs: 62, fat: 23 },
    tags: ["vegetarian", "high-carb", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "8", item: "falafel (store-bought or frozen)" },
      { amount: "½ cup", item: "hummus" },
      { amount: "1", item: "pita bread, quartered" },
      { amount: "1 cup", item: "chopped tomato-cucumber salad", perishable: true, shelfDays: 4 },
      { amount: "¼ cup", item: "pickled turnips or onions" },
      { amount: "2 tbsp", item: "tahini" },
      { amount: "½", item: "lemon, juiced" },
    ],
    steps: [
      "Bake or pan-crisp falafel per package, 12–15 min.",
      "Thin tahini with lemon juice and water to a drizzle.",
      "Swoosh hummus on plates; arrange falafel, salad, pickles, and pita.",
      "Drizzle everything with tahini sauce.",
    ],
  },
  {
    id: "miso-salmon-rice-bowl",
    title: "Miso-Glazed Salmon Rice Bowl",
    cuisine: "Japanese",
    mealType: ["lunch"],
    cookTime: 12,
    prepTime: 8,
    servings: 2,
    macros: { calories: 540, protein: 38, carbs: 52, fat: 20 },
    tags: ["high-protein", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "2 (6 oz)", item: "salmon fillets", perishable: true, shelfDays: 2 },
      { amount: "1½ cups", item: "cooked brown rice" },
      { amount: "2 tbsp", item: "white miso paste" },
      { amount: "1 tbsp", item: "honey" },
      { amount: "1 tbsp", item: "rice vinegar" },
      { amount: "1 cup", item: "steamed broccoli florets", perishable: true, shelfDays: 5 },
      { amount: "1", item: "scallion, sliced", perishable: true, shelfDays: 7 },
    ],
    steps: [
      "Whisk miso, honey, and vinegar; brush over salmon.",
      "Broil salmon 8–10 min until glazed and flaky.",
      "Serve over rice with steamed broccoli.",
      "Scatter scallions on top.",
    ],
  },
  {
    id: "chicken-caesar-light",
    title: "Grilled Chicken Caesar (Lightened Up)",
    cuisine: "Italian-American",
    mealType: ["lunch"],
    cookTime: 12,
    prepTime: 10,
    servings: 2,
    macros: { calories: 420, protein: 44, carbs: 20, fat: 18 },
    tags: ["high-protein", "low-carb", "quick"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "chicken breast", perishable: true, shelfDays: 2 },
      { amount: "1 head", item: "romaine, chopped", perishable: true, shelfDays: 5 },
      { amount: "⅓ cup", item: "Greek yogurt", perishable: true, shelfDays: 10 },
      { amount: "2 tbsp", item: "grated Parmesan", perishable: true, shelfDays: 21 },
      { amount: "1 tsp", item: "Dijon mustard" },
      { amount: "1", item: "garlic clove, grated" },
      { amount: "½", item: "lemon, juiced" },
      { amount: "1 cup", item: "whole grain croutons" },
    ],
    steps: [
      "Dressing: whisk yogurt, Parmesan, Dijon, garlic, and lemon; loosen with water.",
      "Grill seasoned chicken 5–6 min per side; rest and slice.",
      "Toss romaine with dressing and croutons.",
      "Top with sliced chicken and extra Parmesan.",
    ],
  },
  {
    id: "veggie-grain-power-bowl",
    title: "Roasted Veggie & Farro Power Bowl",
    cuisine: "Mediterranean",
    mealType: ["lunch"],
    cookTime: 30,
    prepTime: 10,
    servings: 2,
    macros: { calories: 470, protein: 16, carbs: 70, fat: 16 },
    tags: ["vegetarian", "high-carb", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "farro" },
      { amount: "1", item: "zucchini, chunked", perishable: true, shelfDays: 7 },
      { amount: "1", item: "red bell pepper, chunked", perishable: true, shelfDays: 7 },
      { amount: "1 cup", item: "chickpeas, drained" },
      { amount: "2 tbsp", item: "olive oil" },
      { amount: "¼ cup", item: "hummus" },
      { amount: "1 tsp", item: "smoked paprika" },
      { amount: "2 cups", item: "baby spinach", perishable: true, shelfDays: 5 },
    ],
    steps: [
      "Cook farro in salted water ~25 min; drain.",
      "Roast zucchini, pepper, and chickpeas with oil and paprika at 425°F for 20 min.",
      "Pile farro over spinach; add roasted veg.",
      "Crown with a big spoonful of hummus.",
    ],
  },
  {
    id: "shrimp-tacos-slaw",
    title: "Chili-Lime Shrimp Tacos with Slaw",
    cuisine: "Mexican",
    mealType: ["lunch"],
    cookTime: 8,
    prepTime: 12,
    servings: 2,
    macros: { calories: 440, protein: 34, carbs: 44, fat: 15 },
    tags: ["high-protein", "quick", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "shrimp, peeled", perishable: true, shelfDays: 1 },
      { amount: "6", item: "corn tortillas" },
      { amount: "2 cups", item: "shredded cabbage slaw mix", perishable: true, shelfDays: 5 },
      { amount: "2 tbsp", item: "light mayo" },
      { amount: "2", item: "limes", perishable: true, shelfDays: 14 },
      { amount: "1 tsp", item: "chili powder" },
      { amount: "½ tsp", item: "cumin" },
      { amount: "¼ cup", item: "cilantro", perishable: true, shelfDays: 5 },
      { amount: "1 tbsp", item: "olive oil" },
    ],
    steps: [
      "Toss slaw with mayo and juice of one lime.",
      "Season shrimp with chili powder and cumin; sear in oil 1–2 min per side.",
      "Char tortillas in a dry pan.",
      "Fill with slaw and shrimp; top with cilantro and lime wedges.",
    ],
  },
  {
    id: "italian-chopped-salad",
    title: "Italian Chopped Salad with Salami",
    cuisine: "Italian",
    mealType: ["lunch"],
    cookTime: 0,
    prepTime: 15,
    servings: 2,
    macros: { calories: 450, protein: 24, carbs: 22, fat: 30 },
    tags: ["low-carb", "high-fat", "no-cook", "quick"],
    source: "seed",
    ingredients: [
      { amount: "1 head", item: "iceberg lettuce, chopped", perishable: true, shelfDays: 7 },
      { amount: "4 oz", item: "salami, sliced into ribbons", perishable: true, shelfDays: 14 },
      { amount: "4 oz", item: "provolone, cubed", perishable: true, shelfDays: 14 },
      { amount: "½ cup", item: "chickpeas, drained" },
      { amount: "½ cup", item: "cherry tomatoes, halved", perishable: true, shelfDays: 5 },
      { amount: "¼ cup", item: "pepperoncini, sliced" },
      { amount: "2 tbsp", item: "red wine vinegar" },
      { amount: "3 tbsp", item: "olive oil" },
      { amount: "1 tsp", item: "dried oregano" },
    ],
    steps: [
      "Whisk vinegar, oil, and oregano into a sharp dressing.",
      "Combine lettuce, salami, provolone, chickpeas, tomatoes, and pepperoncini.",
      "Toss hard with the dressing until everything is coated.",
    ],
  },
  {
    id: "butternut-squash-soup-grilled-cheese",
    title: "Butternut Squash Soup & Mini Grilled Cheese",
    cuisine: "American",
    mealType: ["lunch"],
    cookTime: 30,
    prepTime: 10,
    servings: 3,
    macros: { calories: 480, protein: 16, carbs: 56, fat: 22 },
    tags: ["vegetarian", "comfort", "high-carb"],
    source: "seed",
    ingredients: [
      { amount: "1 (2 lb)", item: "butternut squash, cubed", perishable: true, shelfDays: 21 },
      { amount: "1", item: "yellow onion, diced", perishable: true, shelfDays: 14 },
      { amount: "3 cups", item: "vegetable broth" },
      { amount: "½ cup", item: "coconut milk" },
      { amount: "6 slices", item: "sourdough bread" },
      { amount: "1 cup", item: "shredded sharp cheddar", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "butter" },
      { amount: "½ tsp", item: "nutmeg" },
    ],
    steps: [
      "Sauté onion in 1 tbsp butter; add squash and broth. Simmer 20 min until tender.",
      "Blend smooth with coconut milk and nutmeg.",
      "Butter bread, fill with cheddar, and griddle until molten.",
      "Slice into dippers and serve alongside the soup.",
    ],
  },
  {
    id: "tofu-peanut-wrap",
    title: "Crispy Tofu Peanut Wrap",
    cuisine: "Thai-Inspired",
    mealType: ["lunch"],
    cookTime: 12,
    prepTime: 10,
    servings: 2,
    macros: { calories: 490, protein: 24, carbs: 48, fat: 24 },
    tags: ["vegan", "balanced", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "14 oz", item: "extra-firm tofu, sliced", perishable: true, shelfDays: 5 },
      { amount: "2 large", item: "spinach tortillas" },
      { amount: "2 tbsp", item: "peanut butter" },
      { amount: "1 tbsp", item: "soy sauce (low sodium)" },
      { amount: "1 tsp", item: "sriracha" },
      { amount: "1", item: "lime, juiced" },
      { amount: "1 cup", item: "shredded cabbage", perishable: true, shelfDays: 7 },
      { amount: "1", item: "carrot, julienned", perishable: true, shelfDays: 14 },
      { amount: "1 tbsp", item: "neutral oil" },
    ],
    steps: [
      "Press tofu dry; pan-fry in oil until golden on both sides.",
      "Whisk peanut butter, soy, sriracha, lime, and warm water into a sauce.",
      "Toss cabbage and carrot with half the sauce.",
      "Wrap tofu and slaw in tortillas; drizzle remaining sauce inside.",
    ],
  },
  {
    id: "egg-roll-in-a-bowl",
    title: "Egg Roll in a Bowl",
    cuisine: "Chinese-American",
    mealType: ["lunch"],
    cookTime: 15,
    prepTime: 8,
    servings: 2,
    macros: { calories: 380, protein: 32, carbs: 16, fat: 22 },
    tags: ["low-carb", "high-protein", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "ground pork (lean)", perishable: true, shelfDays: 2 },
      { amount: "4 cups", item: "coleslaw mix", perishable: true, shelfDays: 5 },
      { amount: "3", item: "garlic cloves, minced" },
      { amount: "1 tbsp", item: "fresh ginger, grated", perishable: true, shelfDays: 21 },
      { amount: "3 tbsp", item: "soy sauce (low sodium)" },
      { amount: "1 tbsp", item: "rice vinegar" },
      { amount: "1 tsp", item: "sesame oil" },
      { amount: "2", item: "scallions, sliced", perishable: true, shelfDays: 7 },
    ],
    steps: [
      "Brown pork, breaking it up, 6 min. Add garlic and ginger 1 min.",
      "Add coleslaw mix, soy, and vinegar. Stir-fry 4 min until just wilted.",
      "Finish with sesame oil and scallions.",
    ],
  },
  {
    id: "margherita-flatbread-salad",
    title: "Margherita Flatbread with Side Salad",
    cuisine: "Italian",
    mealType: ["lunch"],
    cookTime: 12,
    prepTime: 8,
    servings: 2,
    macros: { calories: 510, protein: 22, carbs: 58, fat: 22 },
    tags: ["vegetarian", "high-carb", "quick"],
    source: "seed",
    ingredients: [
      { amount: "2", item: "naan or flatbreads" },
      { amount: "½ cup", item: "marinara sauce" },
      { amount: "6 oz", item: "fresh mozzarella, torn", perishable: true, shelfDays: 7 },
      { amount: "¼ cup", item: "fresh basil", perishable: true, shelfDays: 4 },
      { amount: "3 cups", item: "mixed greens", perishable: true, shelfDays: 4 },
      { amount: "1 tbsp", item: "balsamic vinegar" },
      { amount: "2 tbsp", item: "olive oil" },
    ],
    steps: [
      "Heat oven to 450°F. Top flatbreads with marinara and mozzarella.",
      "Bake 10–12 min until blistered.",
      "Toss greens with balsamic and 1 tbsp olive oil.",
      "Scatter basil over the flatbreads; drizzle with remaining oil.",
    ],
  },
  {
    id: "chicken-tortilla-soup",
    title: "Chicken Tortilla Soup",
    cuisine: "Mexican",
    mealType: ["lunch"],
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    macros: { calories: 370, protein: 31, carbs: 34, fat: 13 },
    tags: ["high-protein", "low-fat", "meal-prep", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "chicken breast", perishable: true, shelfDays: 2 },
      { amount: "1 can (14 oz)", item: "fire-roasted diced tomatoes" },
      { amount: "1", item: "yellow onion, diced", perishable: true, shelfDays: 14 },
      { amount: "1 can (15 oz)", item: "black beans, drained" },
      { amount: "1 cup", item: "frozen corn" },
      { amount: "4 cups", item: "chicken broth" },
      { amount: "2 tsp", item: "chili powder" },
      { amount: "2", item: "corn tortillas, sliced into strips" },
      { amount: "1", item: "lime", perishable: true, shelfDays: 14 },
      { amount: "1 tbsp", item: "olive oil" },
    ],
    steps: [
      "Sauté onion in oil; add chili powder, tomatoes, broth, and chicken breasts.",
      "Simmer 18 min; remove chicken and shred.",
      "Return chicken with beans and corn; simmer 5 min.",
      "Crisp tortilla strips in a dry pan. Serve soup with strips and lime.",
    ],
  },
  {
    id: "smashed-chickpea-avo-sandwich",
    title: "Smashed Chickpea & Avocado Sandwich",
    cuisine: "American",
    mealType: ["lunch"],
    cookTime: 0,
    prepTime: 10,
    servings: 2,
    macros: { calories: 460, protein: 16, carbs: 58, fat: 20 },
    tags: ["vegan", "no-cook", "quick", "high-carb"],
    source: "seed",
    ingredients: [
      { amount: "1 can (15 oz)", item: "chickpeas, drained" },
      { amount: "1", item: "avocado", perishable: true, shelfDays: 3 },
      { amount: "4 slices", item: "multigrain bread" },
      { amount: "1", item: "lemon, juiced" },
      { amount: "¼", item: "red onion, minced", perishable: true, shelfDays: 14 },
      { amount: "1 handful", item: "sprouts or greens", perishable: true, shelfDays: 3 },
      { amount: "½ tsp", item: "red pepper flakes" },
    ],
    steps: [
      "Mash chickpeas and avocado together, leaving some texture.",
      "Stir in lemon juice, onion, pepper flakes, salt, and pepper.",
      "Toast bread and pile on the smash.",
      "Top with sprouts and close the sandwiches.",
    ],
  },
];
