// 25 additional seed dinners — varied cuisines and macro profiles.

import type { Recipe } from "./meal-data";

export const DINNER_RECIPES_2: Recipe[] = [
  {
    id: "garlic-butter-steak-broccoli",
    title: "Garlic Butter Steak with Charred Broccoli",
    cuisine: "American",
    mealType: ["dinner"],
    cookTime: 20,
    prepTime: 10,
    servings: 2,
    macros: { calories: 560, protein: 48, carbs: 14, fat: 36 },
    tags: ["high-protein", "low-carb", "keto", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "ribeye or sirloin steak", perishable: true, shelfDays: 3 },
      { amount: "1 large head", item: "broccoli, in florets", perishable: true, shelfDays: 5 },
      { amount: "3 tbsp", item: "butter" },
      { amount: "4", item: "garlic cloves, smashed" },
      { amount: "2", item: "sprigs fresh thyme", perishable: true, shelfDays: 7 },
      { amount: "1 tbsp", item: "olive oil" },
      { amount: "½", item: "lemon", perishable: true, shelfDays: 14 },
    ],
    steps: [
      "Roast broccoli with olive oil at 450°F for 18 min until charred at the edges.",
      "Sear steak in a ripping-hot skillet 3–4 min per side.",
      "Add butter, garlic, and thyme; baste 1 min. Rest 5 min.",
      "Slice steak, squeeze lemon over the broccoli, and serve.",
    ],
  },
  {
    id: "beef-broccoli-stir-fry",
    title: "Beef & Broccoli Stir-Fry",
    cuisine: "Chinese",
    mealType: ["dinner"],
    cookTime: 15,
    prepTime: 15,
    servings: 3,
    macros: { calories: 470, protein: 40, carbs: 44, fat: 16 },
    tags: ["high-protein", "quick", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "1¼ lb", item: "flank steak, sliced thin", perishable: true, shelfDays: 3 },
      { amount: "1 large head", item: "broccoli, in florets", perishable: true, shelfDays: 5 },
      { amount: "¼ cup", item: "soy sauce (low sodium)" },
      { amount: "2 tbsp", item: "oyster sauce" },
      { amount: "1 tbsp", item: "cornstarch" },
      { amount: "1 tbsp", item: "brown sugar" },
      { amount: "3", item: "garlic cloves, minced" },
      { amount: "1 tbsp", item: "fresh ginger, grated", perishable: true, shelfDays: 21 },
      { amount: "1½ cups", item: "cooked white rice" },
      { amount: "2 tbsp", item: "neutral oil" },
    ],
    steps: [
      "Toss beef with cornstarch and 1 tbsp soy sauce; rest 10 min.",
      "Sear beef in oil over high heat in batches; set aside.",
      "Stir-fry broccoli 3 min with a splash of water to steam.",
      "Add garlic and ginger, then beef, remaining soy, oyster sauce, and sugar.",
      "Toss until glossy; serve over rice.",
    ],
  },
  {
    id: "pasta-puttanesca",
    title: "Spaghetti Puttanesca",
    cuisine: "Italian",
    mealType: ["dinner"],
    cookTime: 20,
    prepTime: 10,
    servings: 3,
    macros: { calories: 520, protein: 17, carbs: 78, fat: 16 },
    tags: ["high-carb", "quick", "pantry-friendly"],
    source: "seed",
    ingredients: [
      { amount: "12 oz", item: "spaghetti" },
      { amount: "1 can (14 oz)", item: "crushed tomatoes" },
      { amount: "4", item: "anchovy fillets" },
      { amount: "⅓ cup", item: "kalamata olives, halved" },
      { amount: "2 tbsp", item: "capers" },
      { amount: "4", item: "garlic cloves, sliced" },
      { amount: "½ tsp", item: "red pepper flakes" },
      { amount: "3 tbsp", item: "olive oil" },
      { amount: "¼ cup", item: "fresh parsley", perishable: true, shelfDays: 5 },
    ],
    steps: [
      "Cook spaghetti in well-salted water to al dente.",
      "Melt anchovies and garlic in olive oil over medium-low.",
      "Add tomatoes, olives, capers, and pepper flakes. Simmer 10 min.",
      "Toss pasta through the sauce with a splash of pasta water.",
      "Finish with parsley.",
    ],
  },
  {
    id: "baked-cod-mediterranean",
    title: "Mediterranean Baked Cod",
    cuisine: "Greek",
    mealType: ["dinner"],
    cookTime: 22,
    prepTime: 10,
    servings: 2,
    macros: { calories: 380, protein: 38, carbs: 22, fat: 16 },
    tags: ["high-protein", "low-fat", "low-carb", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "2 (6 oz)", item: "cod fillets", perishable: true, shelfDays: 2 },
      { amount: "1 pint", item: "cherry tomatoes", perishable: true, shelfDays: 5 },
      { amount: "⅓ cup", item: "kalamata olives" },
      { amount: "½", item: "red onion, sliced", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "olive oil" },
      { amount: "1 tsp", item: "dried oregano" },
      { amount: "½", item: "lemon", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "fresh parsley", perishable: true, shelfDays: 5 },
    ],
    steps: [
      "Heat oven to 400°F. Toss tomatoes, olives, and onion with oil and oregano in a baking dish.",
      "Roast 10 min until tomatoes burst.",
      "Nestle in cod fillets; season. Bake 10–12 min until flaky.",
      "Finish with lemon and parsley.",
    ],
  },
  {
    id: "pork-tenderloin-apples",
    title: "Pork Tenderloin with Roasted Apples",
    cuisine: "French",
    mealType: ["dinner"],
    cookTime: 30,
    prepTime: 10,
    servings: 3,
    macros: { calories: 460, protein: 40, carbs: 30, fat: 19 },
    tags: ["high-protein", "balanced", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 (1¼ lb)", item: "pork tenderloin", perishable: true, shelfDays: 3 },
      { amount: "2", item: "apples, wedged", perishable: true, shelfDays: 14 },
      { amount: "1", item: "red onion, wedged", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "olive oil" },
      { amount: "1 tbsp", item: "Dijon mustard" },
      { amount: "1 tbsp", item: "maple syrup" },
      { amount: "2", item: "sprigs fresh rosemary", perishable: true, shelfDays: 7 },
    ],
    steps: [
      "Heat oven to 425°F. Rub pork with Dijon, maple, salt, and pepper.",
      "Sear pork in an oven-safe skillet 2 min per side.",
      "Scatter apples, onion, and rosemary around; drizzle with oil.",
      "Roast 18–20 min to 145°F internal. Rest 5 min, slice thick.",
    ],
  },
  {
    id: "thai-green-curry-chicken",
    title: "Thai Green Curry with Chicken",
    cuisine: "Thai",
    mealType: ["dinner"],
    cookTime: 25,
    prepTime: 12,
    servings: 3,
    macros: { calories: 590, protein: 36, carbs: 48, fat: 28 },
    tags: ["high-fat", "spicy", "gluten-free", "comfort"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "chicken breast, sliced", perishable: true, shelfDays: 2 },
      { amount: "3 tbsp", item: "green curry paste" },
      { amount: "1 can (14 oz)", item: "coconut milk" },
      { amount: "1", item: "red bell pepper, sliced", perishable: true, shelfDays: 7 },
      { amount: "1 cup", item: "snap peas", perishable: true, shelfDays: 5 },
      { amount: "1", item: "Thai eggplant or zucchini, chunked", perishable: true, shelfDays: 7 },
      { amount: "1 tbsp", item: "fish sauce" },
      { amount: "1 tsp", item: "brown sugar" },
      { amount: "1 cup", item: "jasmine rice" },
      { amount: "¼ cup", item: "Thai basil", perishable: true, shelfDays: 4 },
    ],
    steps: [
      "Fry curry paste in the thick top of the coconut milk 2 min until fragrant.",
      "Add chicken; coat and cook 4 min.",
      "Pour in remaining coconut milk, fish sauce, and sugar. Add vegetables.",
      "Simmer 12 min. Cook rice meanwhile.",
      "Tear in basil off the heat; serve over rice.",
    ],
  },
  {
    id: "stuffed-bell-peppers-turkey",
    title: "Turkey & Rice Stuffed Bell Peppers",
    cuisine: "American",
    mealType: ["dinner"],
    cookTime: 40,
    prepTime: 15,
    servings: 4,
    macros: { calories: 420, protein: 34, carbs: 38, fat: 15 },
    tags: ["high-protein", "balanced", "meal-prep", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "4 large", item: "bell peppers, tops cut and seeded", perishable: true, shelfDays: 7 },
      { amount: "1 lb", item: "ground turkey", perishable: true, shelfDays: 2 },
      { amount: "1 cup", item: "cooked rice" },
      { amount: "1 can (14 oz)", item: "diced tomatoes, drained" },
      { amount: "1", item: "yellow onion, diced", perishable: true, shelfDays: 14 },
      { amount: "1 cup", item: "shredded mozzarella", perishable: true, shelfDays: 14 },
      { amount: "2 tsp", item: "Italian seasoning" },
      { amount: "1 tbsp", item: "olive oil" },
    ],
    steps: [
      "Heat oven to 375°F. Brown turkey with onion and Italian seasoning.",
      "Stir in rice and tomatoes; season well.",
      "Stuff peppers; stand them in a baking dish with a splash of water.",
      "Cover with foil; bake 30 min. Uncover, top with mozzarella, bake 8 min more.",
    ],
  },
  {
    id: "miso-ramen-quick",
    title: "Quick Miso Ramen with Soft Egg",
    cuisine: "Japanese",
    mealType: ["dinner"],
    cookTime: 20,
    prepTime: 10,
    servings: 2,
    macros: { calories: 540, protein: 28, carbs: 68, fat: 18 },
    tags: ["high-carb", "comfort", "quick"],
    source: "seed",
    ingredients: [
      { amount: "2 portions", item: "fresh ramen noodles" },
      { amount: "4 cups", item: "chicken broth" },
      { amount: "3 tbsp", item: "white miso paste" },
      { amount: "2", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "1 cup", item: "shiitake mushrooms, sliced", perishable: true, shelfDays: 5 },
      { amount: "1 cup", item: "baby bok choy, halved", perishable: true, shelfDays: 4 },
      { amount: "2", item: "scallions, sliced", perishable: true, shelfDays: 7 },
      { amount: "1 tbsp", item: "sesame oil" },
      { amount: "1 sheet", item: "nori, quartered" },
    ],
    steps: [
      "Soft-boil eggs 6½ min; peel and halve.",
      "Sauté shiitakes in sesame oil; add broth and bring to a simmer.",
      "Whisk miso into a ladle of broth, then return to the pot (don't boil).",
      "Cook noodles and bok choy in the broth 2–3 min.",
      "Bowl up with egg, scallions, and nori.",
    ],
  },
  {
    id: "carne-asada-bowls",
    title: "Carne Asada Burrito Bowls",
    cuisine: "Mexican",
    mealType: ["dinner"],
    cookTime: 15,
    prepTime: 20,
    servings: 3,
    macros: { calories: 610, protein: 44, carbs: 56, fat: 23 },
    tags: ["high-protein", "balanced", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1¼ lb", item: "flank steak", perishable: true, shelfDays: 3 },
      { amount: "2", item: "limes, juiced", perishable: true, shelfDays: 14 },
      { amount: "3", item: "garlic cloves, minced" },
      { amount: "1 tsp", item: "cumin" },
      { amount: "1½ cups", item: "cilantro-lime rice" },
      { amount: "1 can (15 oz)", item: "pinto beans, warmed" },
      { amount: "1", item: "avocado, sliced", perishable: true, shelfDays: 3 },
      { amount: "½ cup", item: "pico de gallo", perishable: true, shelfDays: 4 },
      { amount: "¼ cup", item: "cotija cheese", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "olive oil" },
    ],
    steps: [
      "Marinate steak in lime juice, garlic, cumin, and oil, 15 min.",
      "Sear over high heat 4–5 min per side for medium. Rest, then slice thin against the grain.",
      "Build bowls: rice, beans, steak.",
      "Top with avocado, pico, and cotija.",
    ],
  },
  {
    id: "eggplant-parm-lighter",
    title: "Sheet-Pan Eggplant Parmesan",
    cuisine: "Italian",
    mealType: ["dinner"],
    cookTime: 35,
    prepTime: 15,
    servings: 3,
    macros: { calories: 450, protein: 22, carbs: 42, fat: 23 },
    tags: ["vegetarian", "comfort", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "1 large", item: "eggplant, sliced into rounds", perishable: true, shelfDays: 7 },
      { amount: "1 cup", item: "panko breadcrumbs" },
      { amount: "½ cup", item: "grated Parmesan", perishable: true, shelfDays: 21 },
      { amount: "2", item: "eggs, beaten", perishable: true, shelfDays: 21 },
      { amount: "1½ cups", item: "marinara sauce" },
      { amount: "8 oz", item: "fresh mozzarella, sliced", perishable: true, shelfDays: 7 },
      { amount: "¼ cup", item: "fresh basil", perishable: true, shelfDays: 4 },
      { amount: "2 tbsp", item: "olive oil" },
    ],
    steps: [
      "Heat oven to 425°F. Dip eggplant in egg, then panko mixed with half the Parmesan.",
      "Arrange on an oiled sheet pan; bake 20 min, flipping once.",
      "Spoon marinara on each round; top with mozzarella and remaining Parmesan.",
      "Bake 10 min until bubbling. Scatter basil.",
    ],
  },
  {
    id: "salmon-teriyaki-soba",
    title: "Teriyaki Salmon with Soba",
    cuisine: "Japanese",
    mealType: ["dinner"],
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    macros: { calories: 580, protein: 42, carbs: 58, fat: 20 },
    tags: ["high-protein", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "2 (6 oz)", item: "salmon fillets", perishable: true, shelfDays: 2 },
      { amount: "6 oz", item: "soba noodles" },
      { amount: "3 tbsp", item: "soy sauce (low sodium)" },
      { amount: "2 tbsp", item: "mirin" },
      { amount: "1 tbsp", item: "honey" },
      { amount: "1 tbsp", item: "fresh ginger, grated", perishable: true, shelfDays: 21 },
      { amount: "1 cup", item: "snap peas", perishable: true, shelfDays: 5 },
      { amount: "1 tsp", item: "sesame seeds" },
    ],
    steps: [
      "Simmer soy, mirin, honey, and ginger 3 min into a glaze.",
      "Pan-sear salmon 3 min skin-side down; flip, brush with glaze, cook 3 min.",
      "Cook soba; blanch snap peas in the same pot at the end.",
      "Toss noodles with remaining glaze. Plate with salmon and sesame seeds.",
    ],
  },
  {
    id: "white-bean-kale-sausage-skillet",
    title: "Italian Sausage, White Bean & Kale Skillet",
    cuisine: "Italian",
    mealType: ["dinner"],
    cookTime: 22,
    prepTime: 8,
    servings: 3,
    macros: { calories: 480, protein: 30, carbs: 36, fat: 24 },
    tags: ["balanced", "one-pan", "gluten-free", "comfort"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "Italian chicken sausage", perishable: true, shelfDays: 3 },
      { amount: "1 can (15 oz)", item: "cannellini beans, drained" },
      { amount: "1 bunch", item: "lacinato kale, ribboned", perishable: true, shelfDays: 5 },
      { amount: "4", item: "garlic cloves, sliced" },
      { amount: "1 cup", item: "chicken broth" },
      { amount: "¼ cup", item: "grated Parmesan", perishable: true, shelfDays: 21 },
      { amount: "2 tbsp", item: "olive oil" },
      { amount: "½ tsp", item: "red pepper flakes" },
    ],
    steps: [
      "Brown sausage slices in olive oil; set aside.",
      "Soften garlic and pepper flakes in the drippings.",
      "Add kale and broth; cover 3 min to wilt.",
      "Return sausage with beans; simmer 5 min. Shower with Parmesan.",
    ],
  },
  {
    id: "korean-beef-bowls",
    title: "Korean Ground Beef Bowls",
    cuisine: "Korean",
    mealType: ["dinner"],
    cookTime: 15,
    prepTime: 8,
    servings: 3,
    macros: { calories: 530, protein: 35, carbs: 54, fat: 19 },
    tags: ["high-protein", "quick", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "ground beef (90% lean)", perishable: true, shelfDays: 2 },
      { amount: "1½ cups", item: "cooked white rice" },
      { amount: "3 tbsp", item: "soy sauce (low sodium)" },
      { amount: "1 tbsp", item: "brown sugar" },
      { amount: "1 tbsp", item: "sesame oil" },
      { amount: "1 tbsp", item: "gochujang" },
      { amount: "3", item: "garlic cloves, minced" },
      { amount: "1 cup", item: "steamed broccoli", perishable: true, shelfDays: 5 },
      { amount: "2", item: "scallions, sliced", perishable: true, shelfDays: 7 },
      { amount: "1 tsp", item: "sesame seeds" },
    ],
    steps: [
      "Brown beef with garlic, breaking it up.",
      "Stir in soy, sugar, gochujang, and sesame oil; simmer 2 min.",
      "Serve over rice with broccoli.",
      "Top with scallions and sesame seeds.",
    ],
  },
  {
    id: "lemon-herb-roast-chicken-veg",
    title: "Lemon-Herb Roast Chicken Thighs & Potatoes",
    cuisine: "French",
    mealType: ["dinner"],
    cookTime: 45,
    prepTime: 10,
    servings: 4,
    macros: { calories: 540, protein: 38, carbs: 34, fat: 28 },
    tags: ["one-pan", "comfort", "gluten-free", "balanced"],
    source: "seed",
    ingredients: [
      { amount: "8", item: "bone-in chicken thighs", perishable: true, shelfDays: 2 },
      { amount: "1½ lb", item: "baby potatoes, halved", perishable: true, shelfDays: 21 },
      { amount: "1", item: "lemon, sliced", perishable: true, shelfDays: 14 },
      { amount: "4", item: "garlic cloves, smashed" },
      { amount: "2", item: "sprigs fresh rosemary", perishable: true, shelfDays: 7 },
      { amount: "3 tbsp", item: "olive oil" },
      { amount: "1 tsp", item: "dried thyme" },
    ],
    steps: [
      "Heat oven to 425°F. Toss potatoes, lemon, and garlic with half the oil on a sheet pan.",
      "Rub chicken with remaining oil, thyme, salt, and pepper; nestle on top.",
      "Roast 40–45 min until chicken skin is crisp and potatoes are tender.",
      "Rest 5 min; spoon pan juices over everything.",
    ],
  },
  {
    id: "shrimp-scampi-zoodles",
    title: "Shrimp Scampi with Zucchini Noodles",
    cuisine: "Italian",
    mealType: ["dinner"],
    cookTime: 12,
    prepTime: 10,
    servings: 2,
    macros: { calories: 340, protein: 34, carbs: 14, fat: 18 },
    tags: ["low-carb", "high-protein", "low-fat", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 lb", item: "shrimp, peeled", perishable: true, shelfDays: 1 },
      { amount: "3 medium", item: "zucchini, spiralized", perishable: true, shelfDays: 7 },
      { amount: "4", item: "garlic cloves, sliced" },
      { amount: "2 tbsp", item: "butter" },
      { amount: "1 tbsp", item: "olive oil" },
      { amount: "¼ cup", item: "dry white wine or broth" },
      { amount: "½", item: "lemon, juiced", perishable: true, shelfDays: 14 },
      { amount: "¼ tsp", item: "red pepper flakes" },
      { amount: "2 tbsp", item: "fresh parsley", perishable: true, shelfDays: 5 },
    ],
    steps: [
      "Sauté garlic and pepper flakes in oil and butter 1 min.",
      "Add shrimp; cook 1–2 min per side. Remove.",
      "Deglaze with wine and lemon; reduce 2 min.",
      "Toss zoodles in the sauce 2 min. Return shrimp; finish with parsley.",
    ],
  },
  {
    id: "moroccan-chickpea-tagine",
    title: "Moroccan Chickpea & Apricot Tagine",
    cuisine: "Moroccan",
    mealType: ["dinner"],
    cookTime: 30,
    prepTime: 12,
    servings: 4,
    macros: { calories: 420, protein: 13, carbs: 70, fat: 11 },
    tags: ["vegan", "high-carb", "low-fat", "meal-prep", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "2 cans (15 oz)", item: "chickpeas, drained" },
      { amount: "1 can (14 oz)", item: "diced tomatoes" },
      { amount: "½ cup", item: "dried apricots, halved" },
      { amount: "1", item: "yellow onion, diced", perishable: true, shelfDays: 14 },
      { amount: "2", item: "carrots, chunked", perishable: true, shelfDays: 14 },
      { amount: "2 tsp", item: "ras el hanout" },
      { amount: "1 tsp", item: "cinnamon" },
      { amount: "2 cups", item: "vegetable broth" },
      { amount: "1 cup", item: "couscous" },
      { amount: "¼ cup", item: "cilantro", perishable: true, shelfDays: 5 },
      { amount: "2 tbsp", item: "olive oil" },
    ],
    steps: [
      "Soften onion and carrot in oil; bloom ras el hanout and cinnamon 1 min.",
      "Add chickpeas, tomatoes, apricots, and broth. Simmer 25 min until thick.",
      "Steam couscous per package.",
      "Serve tagine over couscous with cilantro.",
    ],
  },
  {
    id: "blackened-fish-grits",
    title: "Blackened Catfish with Cheddar Grits",
    cuisine: "Southern",
    mealType: ["dinner"],
    cookTime: 25,
    prepTime: 10,
    servings: 2,
    macros: { calories: 560, protein: 40, carbs: 44, fat: 25 },
    tags: ["high-protein", "comfort", "spicy", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "2 (6 oz)", item: "catfish or tilapia fillets", perishable: true, shelfDays: 2 },
      { amount: "¾ cup", item: "stone-ground grits" },
      { amount: "¾ cup", item: "shredded sharp cheddar", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "blackening seasoning" },
      { amount: "2 tbsp", item: "butter" },
      { amount: "1 tbsp", item: "olive oil" },
      { amount: "2", item: "scallions, sliced", perishable: true, shelfDays: 7 },
      { amount: "½", item: "lemon", perishable: true, shelfDays: 14 },
    ],
    steps: [
      "Simmer grits in salted water ~20 min; stir in cheddar and 1 tbsp butter.",
      "Coat fish heavily in blackening seasoning.",
      "Sear in oil and butter 3–4 min per side until a dark crust forms.",
      "Serve over grits with scallions and a lemon squeeze.",
    ],
  },
  {
    id: "chicken-fajita-skillet",
    title: "Chicken Fajita Skillet",
    cuisine: "Mexican",
    mealType: ["dinner"],
    cookTime: 18,
    prepTime: 12,
    servings: 3,
    macros: { calories: 470, protein: 40, carbs: 38, fat: 18 },
    tags: ["high-protein", "one-pan", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1¼ lb", item: "chicken breast, sliced", perishable: true, shelfDays: 2 },
      { amount: "2", item: "bell peppers, sliced", perishable: true, shelfDays: 7 },
      { amount: "1", item: "yellow onion, sliced", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "fajita seasoning" },
      { amount: "6", item: "corn tortillas" },
      { amount: "½ cup", item: "sour cream", perishable: true, shelfDays: 10 },
      { amount: "1", item: "lime", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "olive oil" },
    ],
    steps: [
      "Toss chicken with fajita seasoning.",
      "Sear chicken in a hot skillet 5–6 min; set aside.",
      "Char peppers and onion 6 min; return chicken and toss.",
      "Serve sizzling with warm tortillas, sour cream, and lime.",
    ],
  },
  {
    id: "mushroom-risotto",
    title: "Mushroom Parmesan Risotto",
    cuisine: "Italian",
    mealType: ["dinner"],
    cookTime: 35,
    prepTime: 10,
    servings: 3,
    macros: { calories: 510, protein: 14, carbs: 72, fat: 18 },
    tags: ["vegetarian", "high-carb", "comfort", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1¼ cups", item: "arborio rice" },
      { amount: "1 lb", item: "cremini mushrooms, sliced", perishable: true, shelfDays: 5 },
      { amount: "5 cups", item: "vegetable broth, warm" },
      { amount: "½ cup", item: "dry white wine" },
      { amount: "1", item: "shallot, minced", perishable: true, shelfDays: 14 },
      { amount: "½ cup", item: "grated Parmesan", perishable: true, shelfDays: 21 },
      { amount: "3 tbsp", item: "butter" },
      { amount: "2 tbsp", item: "fresh thyme leaves", perishable: true, shelfDays: 7 },
    ],
    steps: [
      "Brown mushrooms in 1 tbsp butter; season and set aside.",
      "Soften shallot in remaining butter. Toast rice 2 min.",
      "Deglaze with wine. Add warm broth a ladle at a time, stirring, ~22 min.",
      "Fold in mushrooms, Parmesan, and thyme. Rest 2 min before serving.",
    ],
  },
  {
    id: "greek-turkey-meatballs-orzo",
    title: "Greek Turkey Meatballs with Lemon Orzo",
    cuisine: "Greek",
    mealType: ["dinner"],
    cookTime: 25,
    prepTime: 15,
    servings: 3,
    macros: { calories: 490, protein: 38, carbs: 48, fat: 17 },
    tags: ["high-protein", "balanced", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "1¼ lb", item: "ground turkey", perishable: true, shelfDays: 2 },
      { amount: "1 cup", item: "orzo" },
      { amount: "¼ cup", item: "breadcrumbs" },
      { amount: "1", item: "egg", perishable: true, shelfDays: 21 },
      { amount: "2 tsp", item: "dried oregano" },
      { amount: "3 oz", item: "feta, crumbled", perishable: true, shelfDays: 14 },
      { amount: "1", item: "lemon", perishable: true, shelfDays: 14 },
      { amount: "2 cups", item: "baby spinach", perishable: true, shelfDays: 5 },
      { amount: "2 tbsp", item: "olive oil" },
    ],
    steps: [
      "Mix turkey, breadcrumbs, egg, oregano, and half the feta; roll into 15 meatballs.",
      "Brown in olive oil ~10 min until cooked through.",
      "Cook orzo; drain, then wilt in spinach with lemon zest and juice.",
      "Plate orzo, meatballs, and remaining feta.",
    ],
  },
  {
    id: "cauliflower-power-curry",
    title: "Cauliflower & Lentil Coconut Curry",
    cuisine: "Indian",
    mealType: ["dinner"],
    cookTime: 28,
    prepTime: 10,
    servings: 4,
    macros: { calories: 390, protein: 15, carbs: 50, fat: 16 },
    tags: ["vegan", "high-carb", "gluten-free", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "1 head", item: "cauliflower, in florets", perishable: true, shelfDays: 7 },
      { amount: "1 cup", item: "red lentils, rinsed" },
      { amount: "1 can (14 oz)", item: "coconut milk" },
      { amount: "1 can (14 oz)", item: "diced tomatoes" },
      { amount: "1", item: "yellow onion, diced", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "curry powder" },
      { amount: "1 tbsp", item: "fresh ginger, grated", perishable: true, shelfDays: 21 },
      { amount: "2 cups", item: "vegetable broth" },
      { amount: "¼ cup", item: "cilantro", perishable: true, shelfDays: 5 },
      { amount: "2 tbsp", item: "coconut oil" },
    ],
    steps: [
      "Soften onion in coconut oil; bloom curry powder and ginger 1 min.",
      "Add lentils, tomatoes, broth, and cauliflower. Simmer 18 min.",
      "Stir in coconut milk; simmer 5 min more until creamy.",
      "Finish with cilantro. Serve alone or over rice.",
    ],
  },
  {
    id: "bbq-chicken-sweet-potato",
    title: "BBQ Chicken-Stuffed Sweet Potatoes",
    cuisine: "American",
    mealType: ["dinner"],
    cookTime: 50,
    prepTime: 10,
    servings: 2,
    macros: { calories: 480, protein: 40, carbs: 56, fat: 11 },
    tags: ["high-protein", "low-fat", "high-carb", "gluten-free", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "2 large", item: "sweet potatoes", perishable: true, shelfDays: 21 },
      { amount: "2", item: "chicken breasts", perishable: true, shelfDays: 2 },
      { amount: "⅓ cup", item: "BBQ sauce" },
      { amount: "¼ cup", item: "Greek yogurt", perishable: true, shelfDays: 10 },
      { amount: "2", item: "scallions, sliced", perishable: true, shelfDays: 7 },
      { amount: "½ cup", item: "shredded red cabbage", perishable: true, shelfDays: 7 },
    ],
    steps: [
      "Bake sweet potatoes at 425°F for 45–50 min until collapsing.",
      "Poach chicken 15 min; shred and toss with BBQ sauce.",
      "Split potatoes; pile in BBQ chicken.",
      "Top with yogurt, cabbage, and scallions.",
    ],
  },
  {
    id: "pad-see-ew",
    title: "Chicken Pad See Ew",
    cuisine: "Thai",
    mealType: ["dinner"],
    cookTime: 15,
    prepTime: 15,
    servings: 2,
    macros: { calories: 590, protein: 36, carbs: 72, fat: 17 },
    tags: ["high-carb", "quick"],
    source: "seed",
    ingredients: [
      { amount: "8 oz", item: "wide rice noodles" },
      { amount: "12 oz", item: "chicken thighs, sliced", perishable: true, shelfDays: 2 },
      { amount: "2 cups", item: "Chinese broccoli or broccolini", perishable: true, shelfDays: 5 },
      { amount: "2", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "2 tbsp", item: "dark soy sauce" },
      { amount: "1 tbsp", item: "oyster sauce" },
      { amount: "1 tbsp", item: "brown sugar" },
      { amount: "3", item: "garlic cloves, minced" },
      { amount: "2 tbsp", item: "neutral oil" },
    ],
    steps: [
      "Soak/cook rice noodles until just pliable.",
      "Stir-fry chicken in oil over high heat; add garlic.",
      "Push aside; scramble eggs in the pan.",
      "Add noodles, greens, soy, oyster sauce, and sugar. Char 2–3 min, tossing minimally.",
    ],
  },
  {
    id: "tuscan-butter-salmon",
    title: "Tuscan Butter Salmon",
    cuisine: "Italian",
    mealType: ["dinner"],
    cookTime: 18,
    prepTime: 8,
    servings: 2,
    macros: { calories: 550, protein: 40, carbs: 12, fat: 38 },
    tags: ["high-fat", "low-carb", "keto", "high-protein", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "2 (6 oz)", item: "salmon fillets", perishable: true, shelfDays: 2 },
      { amount: "¾ cup", item: "heavy cream", perishable: true, shelfDays: 10 },
      { amount: "1 cup", item: "cherry tomatoes, halved", perishable: true, shelfDays: 5 },
      { amount: "2 cups", item: "baby spinach", perishable: true, shelfDays: 5 },
      { amount: "3", item: "garlic cloves, minced" },
      { amount: "¼ cup", item: "grated Parmesan", perishable: true, shelfDays: 21 },
      { amount: "2 tbsp", item: "butter" },
      { amount: "1 tsp", item: "Italian seasoning" },
    ],
    steps: [
      "Sear seasoned salmon in butter 4 min per side; set aside.",
      "Sauté garlic and tomatoes 2 min.",
      "Add cream, Parmesan, and Italian seasoning; simmer 3 min. Wilt in spinach.",
      "Return salmon and spoon sauce over to finish.",
    ],
  },
  {
    id: "smoky-black-bean-sweet-potato-chili",
    title: "Smoky Black Bean & Sweet Potato Chili",
    cuisine: "American",
    mealType: ["dinner"],
    cookTime: 35,
    prepTime: 10,
    servings: 4,
    macros: { calories: 360, protein: 14, carbs: 62, fat: 8 },
    tags: ["vegan", "low-fat", "high-carb", "meal-prep", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "2 cans (15 oz)", item: "black beans, drained" },
      { amount: "1 large", item: "sweet potato, diced", perishable: true, shelfDays: 21 },
      { amount: "1 can (14 oz)", item: "fire-roasted diced tomatoes" },
      { amount: "1", item: "yellow onion, diced", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "chili powder" },
      { amount: "1 tsp", item: "smoked paprika" },
      { amount: "1 tsp", item: "cocoa powder" },
      { amount: "2 cups", item: "vegetable broth" },
      { amount: "1", item: "lime", perishable: true, shelfDays: 14 },
      { amount: "1 tbsp", item: "olive oil" },
    ],
    steps: [
      "Soften onion in oil; bloom chili powder, paprika, and cocoa 1 min.",
      "Add sweet potato, beans, tomatoes, and broth.",
      "Simmer 25–30 min until sweet potato is tender and chili is thick.",
      "Brighten with lime juice before serving.",
    ],
  },
];
