// 25 additional cheat-day recipes — 7 breakfast, 8 lunch, 10 dinner.
// Indulgent by design; macros are honest.

import type { Recipe } from "./meal-data";

export const CHEAT_RECIPES_2: Recipe[] = [
  // ── Breakfast cheats (7) ──────────────────────────────────────────
  {
    id: "cinnamon-roll-french-toast",
    title: "Cinnamon Roll French Toast Bake",
    cuisine: "American",
    mealType: ["breakfast"],
    cookTime: 30,
    prepTime: 10,
    servings: 4,
    macros: { calories: 690, protein: 13, carbs: 88, fat: 32 },
    tags: ["cheat-day", "indulgent", "sweet"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "2 cans", item: "refrigerated cinnamon rolls with icing", perishable: true, shelfDays: 14 },
      { amount: "4", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "½ cup", item: "heavy cream", perishable: true, shelfDays: 10 },
      { amount: "1 tsp", item: "vanilla extract" },
      { amount: "1 tsp", item: "cinnamon" },
      { amount: "¼ cup", item: "maple syrup" },
      { amount: "2 tbsp", item: "butter" },
    ],
    steps: [
      "Heat oven to 375°F. Butter a baking dish.",
      "Quarter the cinnamon rolls and scatter in the dish.",
      "Whisk eggs, cream, vanilla, and cinnamon; pour over.",
      "Bake 25–28 min until puffed. Drizzle with icing and maple syrup.",
    ],
  },
  {
    id: "chicken-and-waffles",
    title: "Fried Chicken & Waffles",
    cuisine: "Southern",
    mealType: ["breakfast"],
    cookTime: 30,
    prepTime: 20,
    servings: 2,
    macros: { calories: 890, protein: 45, carbs: 78, fat: 44 },
    tags: ["cheat-day", "indulgent", "high-protein"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "4", item: "chicken thighs, boneless", perishable: true, shelfDays: 2 },
      { amount: "1 cup", item: "buttermilk", perishable: true, shelfDays: 10 },
      { amount: "1½ cups", item: "flour" },
      { amount: "1 tbsp", item: "hot sauce" },
      { amount: "2", item: "Belgian waffles (frozen or homemade)" },
      { amount: "¼ cup", item: "maple syrup" },
      { amount: "2 tbsp", item: "butter" },
      { amount: "2 cups", item: "neutral oil, for frying" },
      { amount: "1 tsp", item: "cayenne pepper" },
    ],
    steps: [
      "Soak chicken in buttermilk and hot sauce 15 min (or overnight).",
      "Dredge in flour seasoned with cayenne, salt, and pepper.",
      "Shallow-fry 6–7 min per side to 165°F. Drain on a rack.",
      "Toast waffles; butter generously.",
      "Stack chicken on waffles and flood with maple syrup.",
    ],
  },
  {
    id: "loaded-breakfast-poutine",
    title: "Loaded Breakfast Poutine",
    cuisine: "Canadian",
    mealType: ["breakfast"],
    cookTime: 35,
    prepTime: 10,
    servings: 2,
    macros: { calories: 820, protein: 30, carbs: 66, fat: 50 },
    tags: ["cheat-day", "indulgent"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "1 lb", item: "frozen french fries" },
      { amount: "1 cup", item: "cheese curds", perishable: true, shelfDays: 7 },
      { amount: "1 cup", item: "beef gravy" },
      { amount: "4 slices", item: "bacon, chopped", perishable: true, shelfDays: 7 },
      { amount: "2", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "1", item: "scallion, sliced", perishable: true, shelfDays: 7 },
    ],
    steps: [
      "Bake fries extra-crispy per package.",
      "Crisp bacon; fry eggs in the drippings.",
      "Heat gravy until piping.",
      "Pile fries, curds, and bacon; flood with gravy.",
      "Crown with fried eggs and scallions.",
    ],
  },
  {
    id: "nutella-stuffed-pancakes",
    title: "Nutella-Stuffed Pancakes with Strawberries",
    cuisine: "American",
    mealType: ["breakfast"],
    cookTime: 25,
    prepTime: 15,
    servings: 2,
    macros: { calories: 780, protein: 15, carbs: 98, fat: 36 },
    tags: ["cheat-day", "sweet", "indulgent"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "1½ cups", item: "pancake mix" },
      { amount: "½ cup", item: "Nutella" },
      { amount: "1 cup", item: "milk", perishable: true, shelfDays: 7 },
      { amount: "1", item: "egg", perishable: true, shelfDays: 21 },
      { amount: "1 cup", item: "strawberries, sliced", perishable: true, shelfDays: 4 },
      { amount: "2 tbsp", item: "butter" },
      { amount: "2 tbsp", item: "powdered sugar" },
    ],
    steps: [
      "Freeze 6 spoonfuls of Nutella on parchment 10 min until firm.",
      "Make batter with mix, milk, and egg.",
      "Pour a small round, place a Nutella disk in the center, cover with more batter.",
      "Cook in butter 2–3 min per side.",
      "Top with strawberries and a snowfall of powdered sugar.",
    ],
  },
  {
    id: "biscuits-sausage-gravy",
    title: "Buttermilk Biscuits & Sausage Gravy",
    cuisine: "Southern",
    mealType: ["breakfast"],
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    macros: { calories: 740, protein: 22, carbs: 58, fat: 47 },
    tags: ["cheat-day", "indulgent", "comfort"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "1 can (8 ct)", item: "refrigerated buttermilk biscuits", perishable: true, shelfDays: 14 },
      { amount: "1 lb", item: "breakfast sausage", perishable: true, shelfDays: 3 },
      { amount: "¼ cup", item: "flour" },
      { amount: "3 cups", item: "whole milk", perishable: true, shelfDays: 7 },
      { amount: "1 tsp", item: "black pepper" },
      { amount: "¼ tsp", item: "cayenne pepper" },
    ],
    steps: [
      "Bake biscuits per the can.",
      "Brown sausage in a deep skillet, leaving the fat.",
      "Sprinkle flour over; cook 1 min.",
      "Whisk in milk gradually; simmer until spoon-coating thick.",
      "Season aggressively with black pepper. Smother split biscuits.",
    ],
  },
  {
    id: "croissant-breakfast-sandwich",
    title: "Double Bacon Croissant Breakfast Sandwich",
    cuisine: "French-American",
    mealType: ["breakfast"],
    cookTime: 15,
    prepTime: 5,
    servings: 2,
    macros: { calories: 710, protein: 28, carbs: 42, fat: 48 },
    tags: ["cheat-day", "indulgent", "quick"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "2 large", item: "butter croissants" },
      { amount: "6 slices", item: "bacon", perishable: true, shelfDays: 7 },
      { amount: "4", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "2 slices", item: "American cheese", perishable: true, shelfDays: 21 },
      { amount: "1 tbsp", item: "butter" },
      { amount: "1 tbsp", item: "hot honey" },
    ],
    steps: [
      "Crisp bacon; keep warm.",
      "Soft-scramble eggs in butter.",
      "Split and toast croissants cut-side down in the bacon fat.",
      "Layer cheese, eggs, and bacon; drizzle hot honey before closing.",
    ],
  },
  {
    id: "banana-bread-pudding-breakfast",
    title: "Caramelized Banana Bread Pudding",
    cuisine: "American",
    mealType: ["breakfast"],
    cookTime: 40,
    prepTime: 15,
    servings: 4,
    macros: { calories: 650, protein: 14, carbs: 92, fat: 26 },
    tags: ["cheat-day", "sweet", "comfort"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "6 cups", item: "brioche, cubed (day-old)" },
      { amount: "3", item: "ripe bananas, sliced" },
      { amount: "4", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "2 cups", item: "whole milk", perishable: true, shelfDays: 7 },
      { amount: "½ cup", item: "brown sugar" },
      { amount: "1 tsp", item: "vanilla extract" },
      { amount: "1 tsp", item: "cinnamon" },
      { amount: "3 tbsp", item: "butter" },
    ],
    steps: [
      "Caramelize bananas in butter and 2 tbsp brown sugar, 3 min.",
      "Whisk eggs, milk, remaining sugar, vanilla, and cinnamon.",
      "Fold brioche and bananas in a baking dish; pour custard over. Rest 10 min.",
      "Bake at 350°F for 35–40 min until puffed and golden.",
    ],
  },

  // ── Lunch cheats (8) ──────────────────────────────────────────────
  {
    id: "smash-burger-double",
    title: "Double Smash Burger with Special Sauce",
    cuisine: "American",
    mealType: ["lunch"],
    cookTime: 12,
    prepTime: 10,
    servings: 2,
    macros: { calories: 850, protein: 48, carbs: 42, fat: 54 },
    tags: ["cheat-day", "indulgent", "high-protein"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "1 lb", item: "ground beef (80/20)", perishable: true, shelfDays: 2 },
      { amount: "2", item: "potato buns" },
      { amount: "4 slices", item: "American cheese", perishable: true, shelfDays: 21 },
      { amount: "2 tbsp", item: "mayonnaise" },
      { amount: "1 tbsp", item: "ketchup" },
      { amount: "1 tbsp", item: "pickle relish" },
      { amount: "½", item: "white onion, thinly sliced", perishable: true, shelfDays: 14 },
      { amount: "4", item: "pickle slices" },
      { amount: "1 cup", item: "shredded iceberg", perishable: true, shelfDays: 7 },
    ],
    steps: [
      "Special sauce: mix mayo, ketchup, and relish.",
      "Divide beef into 4 loose balls. Smash flat on a screaming-hot griddle.",
      "Season hard; flip at 90 seconds when crusted. Cheese every patty.",
      "Stack two patties per toasted bun with sauce, onion, pickles, and lettuce.",
    ],
  },
  {
    id: "buffalo-chicken-mac",
    title: "Buffalo Chicken Mac & Cheese",
    cuisine: "American",
    mealType: ["lunch"],
    cookTime: 25,
    prepTime: 10,
    servings: 4,
    macros: { calories: 760, protein: 42, carbs: 62, fat: 38 },
    tags: ["cheat-day", "indulgent", "comfort", "spicy"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "12 oz", item: "cavatappi or elbow pasta" },
      { amount: "2 cups", item: "shredded rotisserie chicken", perishable: true, shelfDays: 3 },
      { amount: "½ cup", item: "buffalo sauce" },
      { amount: "2 cups", item: "shredded cheddar", perishable: true, shelfDays: 14 },
      { amount: "1 cup", item: "whole milk", perishable: true, shelfDays: 7 },
      { amount: "2 tbsp", item: "butter" },
      { amount: "2 tbsp", item: "flour" },
      { amount: "⅓ cup", item: "blue cheese crumbles", perishable: true, shelfDays: 14 },
      { amount: "2", item: "scallions, sliced", perishable: true, shelfDays: 7 },
    ],
    steps: [
      "Cook pasta shy of al dente.",
      "Roux: butter and flour, 1 min. Whisk in milk; simmer thick.",
      "Melt in cheddar. Toss chicken with buffalo sauce.",
      "Fold pasta and chicken through the sauce.",
      "Top with blue cheese and scallions; broil 3 min if you want a crust.",
    ],
  },
  {
    id: "philly-cheesesteak",
    title: "Philly Cheesesteak",
    cuisine: "American",
    mealType: ["lunch"],
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    macros: { calories: 780, protein: 46, carbs: 54, fat: 42 },
    tags: ["cheat-day", "indulgent", "high-protein"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "1 lb", item: "ribeye, shaved or sliced paper-thin", perishable: true, shelfDays: 3 },
      { amount: "2", item: "hoagie rolls" },
      { amount: "8 slices", item: "provolone", perishable: true, shelfDays: 14 },
      { amount: "1", item: "yellow onion, sliced", perishable: true, shelfDays: 14 },
      { amount: "1", item: "green bell pepper, sliced", perishable: true, shelfDays: 7 },
      { amount: "2 tbsp", item: "neutral oil" },
      { amount: "1 tbsp", item: "butter" },
    ],
    steps: [
      "Caramelize onion and pepper in oil; set aside.",
      "Sear ribeye on a hot flat-top, chopping with the spatula.",
      "Fold veg back in; portion into two piles. Blanket with provolone.",
      "Butter and toast the rolls; scoop everything in once the cheese melts.",
    ],
  },
  {
    id: "carnitas-quesadilla-grande",
    title: "Carnitas Quesadilla Grande",
    cuisine: "Mexican",
    mealType: ["lunch"],
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    macros: { calories: 820, protein: 44, carbs: 58, fat: 46 },
    tags: ["cheat-day", "indulgent"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "2 extra-large", item: "flour tortillas" },
      { amount: "2 cups", item: "carnitas or pulled pork", perishable: true, shelfDays: 4 },
      { amount: "2 cups", item: "shredded Oaxaca or Jack cheese", perishable: true, shelfDays: 14 },
      { amount: "½ cup", item: "guacamole", perishable: true, shelfDays: 2 },
      { amount: "½ cup", item: "sour cream", perishable: true, shelfDays: 10 },
      { amount: "½ cup", item: "salsa roja" },
      { amount: "1 tbsp", item: "butter" },
    ],
    steps: [
      "Layer half of each tortilla with cheese, carnitas, more cheese.",
      "Fold and griddle in butter 3–4 min per side until shattering-crisp.",
      "Rest 2 min; cut into wedges.",
      "Serve with guacamole, sour cream, and salsa.",
    ],
  },
  {
    id: "fried-chicken-sandwich-nashville",
    title: "Nashville Hot Chicken Sandwich",
    cuisine: "Southern",
    mealType: ["lunch"],
    cookTime: 20,
    prepTime: 15,
    servings: 2,
    macros: { calories: 870, protein: 46, carbs: 64, fat: 48 },
    tags: ["cheat-day", "indulgent", "spicy"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "2", item: "chicken breasts, butterflied", perishable: true, shelfDays: 2 },
      { amount: "1 cup", item: "buttermilk", perishable: true, shelfDays: 10 },
      { amount: "1½ cups", item: "flour" },
      { amount: "2 tbsp", item: "cayenne pepper" },
      { amount: "1 tbsp", item: "brown sugar" },
      { amount: "2", item: "brioche buns" },
      { amount: "½ cup", item: "coleslaw", perishable: true, shelfDays: 4 },
      { amount: "6", item: "pickle slices" },
      { amount: "2 cups", item: "neutral oil, for frying" },
    ],
    steps: [
      "Dip chicken in buttermilk, then seasoned flour; repeat for a thick crust.",
      "Fry 5–6 min per side to 165°F.",
      "Whisk ¼ cup hot frying oil with cayenne and brown sugar; brush all over.",
      "Stack on buns with slaw and pickles.",
    ],
  },
  {
    id: "loaded-carne-fries",
    title: "Loaded Carne Asada Fries",
    cuisine: "Cal-Mex",
    mealType: ["lunch"],
    cookTime: 30,
    prepTime: 15,
    servings: 3,
    macros: { calories: 790, protein: 38, carbs: 62, fat: 44 },
    tags: ["cheat-day", "indulgent"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "1½ lb", item: "frozen french fries" },
      { amount: "12 oz", item: "flank steak", perishable: true, shelfDays: 3 },
      { amount: "1½ cups", item: "shredded Jack cheese", perishable: true, shelfDays: 14 },
      { amount: "½ cup", item: "guacamole", perishable: true, shelfDays: 2 },
      { amount: "½ cup", item: "sour cream", perishable: true, shelfDays: 10 },
      { amount: "½ cup", item: "pico de gallo", perishable: true, shelfDays: 4 },
      { amount: "1", item: "lime", perishable: true, shelfDays: 14 },
      { amount: "1 tbsp", item: "taco seasoning" },
      { amount: "1 tbsp", item: "olive oil" },
    ],
    steps: [
      "Bake fries until deeply crisp.",
      "Rub steak with taco seasoning and oil; sear 4 min per side. Rest and chop.",
      "Blanket hot fries with cheese; broil 2 min.",
      "Load with steak, guac, sour cream, and pico. Lime over everything.",
    ],
  },
  {
    id: "chicago-deep-dish-slice",
    title: "Deep-Dish Sausage Pan Pizza",
    cuisine: "Italian-American",
    mealType: ["lunch"],
    cookTime: 35,
    prepTime: 20,
    servings: 4,
    macros: { calories: 720, protein: 30, carbs: 68, fat: 38 },
    tags: ["cheat-day", "indulgent", "comfort"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "1 lb", item: "pizza dough", perishable: true, shelfDays: 4 },
      { amount: "8 oz", item: "Italian sausage", perishable: true, shelfDays: 3 },
      { amount: "2 cups", item: "shredded mozzarella", perishable: true, shelfDays: 14 },
      { amount: "1½ cups", item: "crushed tomatoes" },
      { amount: "¼ cup", item: "grated Parmesan", perishable: true, shelfDays: 21 },
      { amount: "1 tsp", item: "dried oregano" },
      { amount: "3 tbsp", item: "olive oil" },
    ],
    steps: [
      "Press dough into a generously oiled cast-iron skillet; rest 15 min.",
      "Layer mozzarella first, then crumbled raw sausage.",
      "Top with crushed tomatoes, oregano, and Parmesan.",
      "Bake at 450°F for 28–32 min until the crust is deep golden.",
      "Rest 5 min before slicing.",
    ],
  },
  {
    id: "korean-fried-chicken-wings",
    title: "Korean Fried Chicken Wings",
    cuisine: "Korean",
    mealType: ["lunch"],
    cookTime: 30,
    prepTime: 15,
    servings: 3,
    macros: { calories: 720, protein: 42, carbs: 48, fat: 40 },
    tags: ["cheat-day", "indulgent", "spicy"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "2 lb", item: "chicken wings", perishable: true, shelfDays: 2 },
      { amount: "¾ cup", item: "potato starch or cornstarch" },
      { amount: "3 tbsp", item: "gochujang" },
      { amount: "2 tbsp", item: "honey" },
      { amount: "2 tbsp", item: "soy sauce (low sodium)" },
      { amount: "1 tbsp", item: "rice vinegar" },
      { amount: "3", item: "garlic cloves, minced" },
      { amount: "1 tbsp", item: "sesame seeds" },
      { amount: "3 cups", item: "neutral oil, for frying" },
    ],
    steps: [
      "Toss wings in starch; rest 10 min for a craggy coat.",
      "Fry at 340°F for 8 min; rest 5 min; fry again at 375°F for 4 min until glass-crisp.",
      "Simmer gochujang, honey, soy, vinegar, and garlic 2 min.",
      "Toss wings through the glaze; shower with sesame seeds.",
    ],
  },

  // ── Dinner cheats (10) ────────────────────────────────────────────
  {
    id: "ribeye-loaded-baked-potato",
    title: "Ribeye with Fully Loaded Baked Potato",
    cuisine: "American Steakhouse",
    mealType: ["dinner"],
    cookTime: 60,
    prepTime: 10,
    servings: 2,
    macros: { calories: 940, protein: 58, carbs: 52, fat: 56 },
    tags: ["cheat-day", "indulgent", "high-protein"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "2 (12 oz)", item: "ribeye steaks", perishable: true, shelfDays: 3 },
      { amount: "2 large", item: "russet potatoes", perishable: true, shelfDays: 21 },
      { amount: "4 tbsp", item: "butter" },
      { amount: "½ cup", item: "sour cream", perishable: true, shelfDays: 10 },
      { amount: "1 cup", item: "shredded cheddar", perishable: true, shelfDays: 14 },
      { amount: "4 slices", item: "bacon, crumbled", perishable: true, shelfDays: 7 },
      { amount: "2", item: "scallions, sliced", perishable: true, shelfDays: 7 },
      { amount: "2", item: "garlic cloves, smashed" },
      { amount: "2", item: "sprigs fresh thyme", perishable: true, shelfDays: 7 },
    ],
    steps: [
      "Bake potatoes at 425°F for ~55 min until the skins crackle.",
      "Sear ribeyes in a screaming cast iron, 4 min per side for medium-rare.",
      "Butter-baste with garlic and thyme 1 min. Rest 8 min.",
      "Split potatoes; load with butter, cheddar, sour cream, bacon, and scallions.",
    ],
  },
  {
    id: "lobster-mac-and-cheese",
    title: "Lobster Mac & Cheese",
    cuisine: "New England",
    mealType: ["dinner"],
    cookTime: 35,
    prepTime: 15,
    servings: 4,
    macros: { calories: 820, protein: 38, carbs: 64, fat: 46 },
    tags: ["cheat-day", "indulgent", "comfort"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "12 oz", item: "cavatappi pasta" },
      { amount: "12 oz", item: "cooked lobster meat, chunked", perishable: true, shelfDays: 2 },
      { amount: "2 cups", item: "shredded Gruyère", perishable: true, shelfDays: 14 },
      { amount: "1 cup", item: "shredded white cheddar", perishable: true, shelfDays: 14 },
      { amount: "2½ cups", item: "whole milk", perishable: true, shelfDays: 7 },
      { amount: "3 tbsp", item: "butter" },
      { amount: "3 tbsp", item: "flour" },
      { amount: "½ cup", item: "panko breadcrumbs" },
      { amount: "1 pinch", item: "nutmeg" },
    ],
    steps: [
      "Cook pasta shy of al dente.",
      "Roux, then milk; simmer until thick. Melt in both cheeses with nutmeg.",
      "Fold in pasta and lobster. Transfer to a baking dish.",
      "Top with buttered panko; bake at 400°F for 15 min until bronzed.",
    ],
  },
  {
    id: "shrimp-alfredo-fettuccine",
    title: "Shrimp Alfredo Fettuccine",
    cuisine: "Italian-American",
    mealType: ["dinner"],
    cookTime: 20,
    prepTime: 10,
    servings: 3,
    macros: { calories: 820, protein: 40, carbs: 70, fat: 42 },
    tags: ["cheat-day", "indulgent", "comfort"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "12 oz", item: "fettuccine" },
      { amount: "1 lb", item: "shrimp, peeled", perishable: true, shelfDays: 1 },
      { amount: "1½ cups", item: "heavy cream", perishable: true, shelfDays: 10 },
      { amount: "1 cup", item: "grated Parmesan", perishable: true, shelfDays: 21 },
      { amount: "4 tbsp", item: "butter" },
      { amount: "4", item: "garlic cloves, minced" },
      { amount: "¼ tsp", item: "nutmeg" },
      { amount: "2 tbsp", item: "fresh parsley", perishable: true, shelfDays: 5 },
    ],
    steps: [
      "Cook fettuccine to al dente; reserve a cup of pasta water.",
      "Sauté shrimp in 2 tbsp butter until pink; set aside.",
      "Melt remaining butter with garlic; add cream and simmer 3 min.",
      "Whisk in Parmesan and nutmeg until silky.",
      "Toss pasta and shrimp through the sauce, loosening with pasta water. Finish with parsley.",
    ],
  },
  {
    id: "truffle-mushroom-pizza",
    title: "Truffle Mushroom White Pizza",
    cuisine: "Italian",
    mealType: ["dinner"],
    cookTime: 18,
    prepTime: 20,
    servings: 3,
    macros: { calories: 690, protein: 26, carbs: 70, fat: 35 },
    tags: ["cheat-day", "indulgent", "vegetarian"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "1 lb", item: "pizza dough", perishable: true, shelfDays: 4 },
      { amount: "8 oz", item: "mixed mushrooms, sliced", perishable: true, shelfDays: 5 },
      { amount: "1½ cups", item: "shredded mozzarella", perishable: true, shelfDays: 14 },
      { amount: "½ cup", item: "ricotta", perishable: true, shelfDays: 7 },
      { amount: "¼ cup", item: "grated Parmesan", perishable: true, shelfDays: 21 },
      { amount: "1 tbsp", item: "truffle oil" },
      { amount: "2", item: "garlic cloves, minced" },
      { amount: "2 tbsp", item: "olive oil" },
      { amount: "1 tsp", item: "fresh thyme leaves", perishable: true, shelfDays: 7 },
    ],
    steps: [
      "Heat oven (and stone, if you have one) to 500°F.",
      "Sauté mushrooms with garlic until deeply browned.",
      "Stretch dough; brush with olive oil. Dollop ricotta, scatter mozzarella and mushrooms.",
      "Bake 12–14 min. Finish with Parmesan, thyme, and a thin drizzle of truffle oil.",
    ],
  },
  {
    id: "general-tsos-chicken",
    title: "General Tso's Chicken",
    cuisine: "Chinese-American",
    mealType: ["dinner"],
    cookTime: 25,
    prepTime: 15,
    servings: 3,
    macros: { calories: 750, protein: 38, carbs: 78, fat: 32 },
    tags: ["cheat-day", "indulgent", "spicy"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "1½ lb", item: "chicken thighs, cubed", perishable: true, shelfDays: 2 },
      { amount: "¾ cup", item: "cornstarch" },
      { amount: "¼ cup", item: "soy sauce (low sodium)" },
      { amount: "3 tbsp", item: "rice vinegar" },
      { amount: "3 tbsp", item: "sugar" },
      { amount: "2 tbsp", item: "hoisin sauce" },
      { amount: "6", item: "dried red chiles" },
      { amount: "1½ cups", item: "cooked white rice" },
      { amount: "2", item: "scallions, sliced", perishable: true, shelfDays: 7 },
      { amount: "2 cups", item: "neutral oil, for frying" },
    ],
    steps: [
      "Toss chicken in cornstarch; fry in batches until golden, ~5 min.",
      "Simmer soy, vinegar, sugar, and hoisin with chiles until syrupy.",
      "Toss crispy chicken through the sauce.",
      "Serve over rice with scallions.",
    ],
  },
  {
    id: "carbonara-classic",
    title: "Classic Roman Carbonara",
    cuisine: "Italian",
    mealType: ["dinner"],
    cookTime: 18,
    prepTime: 10,
    servings: 2,
    macros: { calories: 780, protein: 32, carbs: 76, fat: 38 },
    tags: ["cheat-day", "indulgent", "comfort"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "8 oz", item: "spaghetti or rigatoni" },
      { amount: "6 oz", item: "guanciale or pancetta, cubed", perishable: true, shelfDays: 14 },
      { amount: "3", item: "egg yolks", perishable: true, shelfDays: 21 },
      { amount: "1", item: "whole egg", perishable: true, shelfDays: 21 },
      { amount: "1 cup", item: "grated Pecorino Romano", perishable: true, shelfDays: 21 },
      { amount: "2 tsp", item: "coarse black pepper" },
    ],
    steps: [
      "Render guanciale over medium-low until crisp.",
      "Whisk yolks, egg, Pecorino, and pepper.",
      "Cook pasta; reserve a cup of starchy water.",
      "Off heat, toss pasta with guanciale, then the egg mixture, loosening with pasta water into a glossy sauce. Never let it scramble.",
    ],
  },
  {
    id: "bbq-ribs-cornbread",
    title: "Sticky BBQ Ribs with Cornbread",
    cuisine: "Southern BBQ",
    mealType: ["dinner"],
    cookTime: 180,
    prepTime: 15,
    servings: 4,
    macros: { calories: 880, protein: 46, carbs: 64, fat: 48 },
    tags: ["cheat-day", "indulgent", "weekend-project"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "1 rack (3 lb)", item: "pork baby back ribs", perishable: true, shelfDays: 3 },
      { amount: "3 tbsp", item: "BBQ dry rub" },
      { amount: "1 cup", item: "BBQ sauce" },
      { amount: "1 box", item: "cornbread mix" },
      { amount: "1", item: "egg", perishable: true, shelfDays: 21 },
      { amount: "⅓ cup", item: "milk", perishable: true, shelfDays: 7 },
      { amount: "2 tbsp", item: "butter" },
      { amount: "2 tbsp", item: "honey" },
    ],
    steps: [
      "Rub ribs; wrap in foil. Bake at 300°F for 2½ hours until tender.",
      "Bake cornbread per box with egg and milk; brush with honey butter.",
      "Unwrap ribs, lacquer with BBQ sauce.",
      "Broil or grill 5 min until sticky and charred at the edges.",
    ],
  },
  {
    id: "chicken-parm-classic",
    title: "Chicken Parmesan with Spaghetti",
    cuisine: "Italian-American",
    mealType: ["dinner"],
    cookTime: 30,
    prepTime: 15,
    servings: 3,
    macros: { calories: 810, protein: 52, carbs: 70, fat: 36 },
    tags: ["cheat-day", "indulgent", "comfort", "high-protein"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "3", item: "chicken breasts, pounded thin", perishable: true, shelfDays: 2 },
      { amount: "1 cup", item: "Italian breadcrumbs" },
      { amount: "2", item: "eggs, beaten", perishable: true, shelfDays: 21 },
      { amount: "2 cups", item: "marinara sauce" },
      { amount: "8 oz", item: "fresh mozzarella, sliced", perishable: true, shelfDays: 7 },
      { amount: "½ cup", item: "grated Parmesan", perishable: true, shelfDays: 21 },
      { amount: "8 oz", item: "spaghetti" },
      { amount: "¼ cup", item: "fresh basil", perishable: true, shelfDays: 4 },
      { amount: "½ cup", item: "olive oil, for shallow frying" },
    ],
    steps: [
      "Bread chicken: egg, then breadcrumbs mixed with half the Parmesan.",
      "Shallow-fry 3–4 min per side until golden.",
      "Top with marinara and mozzarella; broil until molten.",
      "Toss spaghetti with remaining marinara. Plate with basil and Parmesan.",
    ],
  },
  {
    id: "country-fried-steak",
    title: "Country Fried Steak with Mashed Potatoes & Gravy",
    cuisine: "Southern",
    mealType: ["dinner"],
    cookTime: 35,
    prepTime: 15,
    servings: 3,
    macros: { calories: 840, protein: 44, carbs: 62, fat: 46 },
    tags: ["cheat-day", "indulgent", "comfort"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "3 (6 oz)", item: "cube steaks", perishable: true, shelfDays: 3 },
      { amount: "1½ cups", item: "flour" },
      { amount: "2", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "2 cups", item: "whole milk", perishable: true, shelfDays: 7 },
      { amount: "1½ lb", item: "russet potatoes", perishable: true, shelfDays: 21 },
      { amount: "4 tbsp", item: "butter" },
      { amount: "1 tsp", item: "black pepper" },
      { amount: "½ tsp", item: "cayenne pepper" },
      { amount: "1 cup", item: "neutral oil, for frying" },
    ],
    steps: [
      "Boil potatoes; mash with butter and ½ cup milk.",
      "Dredge steaks: seasoned flour → egg → flour again, pressing for a craggy crust.",
      "Shallow-fry 3–4 min per side until deep golden. Rest on a rack.",
      "Pour off all but 3 tbsp oil; whisk in 3 tbsp flour, then remaining milk. Simmer into a peppery gravy.",
      "Smother steaks and mash with the gravy.",
    ],
  },
  {
    id: "butter-chicken-naan-feast",
    title: "Butter Chicken with Garlic Naan",
    cuisine: "Indian",
    mealType: ["dinner"],
    cookTime: 35,
    prepTime: 15,
    servings: 4,
    macros: { calories: 790, protein: 44, carbs: 58, fat: 42 },
    tags: ["cheat-day", "indulgent", "comfort"],
    source: "seed",
    isCheatDay: true,
    ingredients: [
      { amount: "1½ lb", item: "chicken thighs, cubed", perishable: true, shelfDays: 2 },
      { amount: "½ cup", item: "Greek yogurt", perishable: true, shelfDays: 10 },
      { amount: "2 tbsp", item: "garam masala" },
      { amount: "1 can (14 oz)", item: "tomato purée" },
      { amount: "¾ cup", item: "heavy cream", perishable: true, shelfDays: 10 },
      { amount: "6 tbsp", item: "butter" },
      { amount: "1 tbsp", item: "fresh ginger, grated", perishable: true, shelfDays: 21 },
      { amount: "4", item: "garlic naan breads" },
      { amount: "¼ cup", item: "cilantro", perishable: true, shelfDays: 5 },
    ],
    steps: [
      "Marinate chicken in yogurt and half the garam masala; broil until charred.",
      "Melt butter; cook ginger and remaining spice 1 min. Add tomato purée; simmer 10 min.",
      "Stir in cream and chicken; simmer 10 min until silky.",
      "Char naan over a flame. Finish curry with cilantro and an extra knob of butter.",
    ],
  },
];
