// 40 seed snacks — deliberately low-complication (most are no-cook,
// 1–5 ingredients) so they can be slotted between meals to close
// macro gaps. Tagged by macro profile for the rebalancer.

import type { Recipe } from "./meal-data";

export const SNACK_RECIPES: Recipe[] = [
  {
    id: "snack-whey-shake-water",
    title: "Whey Protein Shake (Water)",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 2,
    servings: 1,
    macros: { calories: 120, protein: 25, carbs: 3, fat: 1 },
    tags: ["high-protein", "low-fat", "low-carb", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 scoop", item: "whey protein powder" },
      { amount: "10 oz", item: "cold water" },
    ],
    steps: ["Shake protein powder with cold water until smooth."],
  },
  {
    id: "snack-whey-shake-milk",
    title: "Whey Protein Shake (Milk)",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 2,
    servings: 1,
    macros: { calories: 270, protein: 33, carbs: 15, fat: 8 },
    tags: ["high-protein", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 scoop", item: "whey protein powder" },
      { amount: "10 oz", item: "whole milk", perishable: true, shelfDays: 7 },
    ],
    steps: ["Shake protein powder with cold milk until smooth."],
  },
  {
    id: "snack-pb-banana-shake",
    title: "Peanut Butter Banana Protein Shake",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 4,
    servings: 1,
    macros: { calories: 390, protein: 32, carbs: 36, fat: 14 },
    tags: ["high-protein", "high-carb", "no-cook", "quick"],
    source: "seed",
    ingredients: [
      { amount: "1 scoop", item: "whey protein powder" },
      { amount: "1", item: "banana" },
      { amount: "1 tbsp", item: "peanut butter" },
      { amount: "1 cup", item: "milk", perishable: true, shelfDays: 7 },
    ],
    steps: ["Blend everything with a few ice cubes until smooth."],
  },
  {
    id: "snack-greek-yogurt-honey",
    title: "Greek Yogurt with Honey",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 2,
    servings: 1,
    macros: { calories: 180, protein: 20, carbs: 22, fat: 1 },
    tags: ["high-protein", "low-fat", "no-cook", "quick", "vegetarian", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "nonfat Greek yogurt", perishable: true, shelfDays: 10 },
      { amount: "1 tbsp", item: "honey" },
    ],
    steps: ["Drizzle honey over yogurt and eat."],
  },
  {
    id: "snack-cottage-cheese-pineapple",
    title: "Cottage Cheese & Pineapple",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 3,
    servings: 1,
    macros: { calories: 210, protein: 24, carbs: 22, fat: 3 },
    tags: ["high-protein", "low-fat", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "low-fat cottage cheese", perishable: true, shelfDays: 7 },
      { amount: "½ cup", item: "pineapple chunks", perishable: true, shelfDays: 4 },
    ],
    steps: ["Top cottage cheese with pineapple."],
  },
  {
    id: "snack-hard-boiled-eggs",
    title: "Hard-Boiled Eggs with Everything Seasoning",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 10,
    prepTime: 2,
    servings: 1,
    macros: { calories: 160, protein: 13, carbs: 1, fat: 11 },
    tags: ["high-protein", "low-carb", "keto", "meal-prep", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "2", item: "eggs", perishable: true, shelfDays: 21 },
      { amount: "½ tsp", item: "everything bagel seasoning" },
    ],
    steps: [
      "Boil eggs 10 min; cool in ice water and peel.",
      "Halve and sprinkle with seasoning. (Make a batch for the week.)",
    ],
  },
  {
    id: "snack-apple-peanut-butter",
    title: "Apple with Peanut Butter",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 3,
    servings: 1,
    macros: { calories: 280, protein: 8, carbs: 34, fat: 16 },
    tags: ["balanced", "no-cook", "quick", "vegetarian", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1", item: "apple, sliced", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "peanut butter" },
    ],
    steps: ["Slice apple and dip in peanut butter."],
  },
  {
    id: "snack-trail-mix",
    title: "DIY Trail Mix",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 3,
    servings: 1,
    macros: { calories: 310, protein: 9, carbs: 28, fat: 20 },
    tags: ["high-fat", "no-cook", "quick", "vegan", "meal-prep"],
    source: "seed",
    ingredients: [
      { amount: "¼ cup", item: "mixed nuts" },
      { amount: "2 tbsp", item: "dried cranberries" },
      { amount: "1 tbsp", item: "dark chocolate chips" },
    ],
    steps: ["Toss together. Portion into bags for the week if prepping."],
  },
  {
    id: "snack-beef-jerky",
    title: "Beef Jerky & String Cheese",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 1,
    servings: 1,
    macros: { calories: 220, protein: 26, carbs: 7, fat: 10 },
    tags: ["high-protein", "low-carb", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1.5 oz", item: "beef jerky" },
      { amount: "1 stick", item: "string cheese", perishable: true, shelfDays: 21 },
    ],
    steps: ["Unwrap and eat. The ultimate zero-effort protein hit."],
  },
  {
    id: "snack-hummus-veggies",
    title: "Hummus with Veggie Sticks",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    macros: { calories: 190, protein: 7, carbs: 22, fat: 9 },
    tags: ["vegan", "low-fat", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "⅓ cup", item: "hummus" },
      { amount: "1", item: "carrot, cut into sticks", perishable: true, shelfDays: 14 },
      { amount: "½", item: "cucumber, cut into sticks", perishable: true, shelfDays: 7 },
    ],
    steps: ["Cut veggies into sticks and dip."],
  },
  {
    id: "snack-rice-cakes-pb",
    title: "Rice Cakes with Peanut Butter & Banana",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 4,
    servings: 1,
    macros: { calories: 290, protein: 9, carbs: 40, fat: 12 },
    tags: ["high-carb", "no-cook", "quick", "vegetarian", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "2", item: "rice cakes" },
      { amount: "1½ tbsp", item: "peanut butter" },
      { amount: "½", item: "banana, sliced" },
    ],
    steps: ["Spread rice cakes with peanut butter; shingle banana on top."],
  },
  {
    id: "snack-tuna-crackers",
    title: "Tuna Packet & Crackers",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 3,
    servings: 1,
    macros: { calories: 230, protein: 22, carbs: 20, fat: 7 },
    tags: ["high-protein", "low-fat", "no-cook", "quick"],
    source: "seed",
    ingredients: [
      { amount: "1 packet (2.6 oz)", item: "flavored tuna" },
      { amount: "10", item: "whole grain crackers" },
    ],
    steps: ["Scoop tuna onto crackers."],
  },
  {
    id: "snack-protein-bar",
    title: "Protein Bar",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 1,
    servings: 1,
    macros: { calories: 210, protein: 20, carbs: 22, fat: 7 },
    tags: ["high-protein", "no-cook", "quick", "portable"],
    source: "seed",
    ingredients: [{ amount: "1", item: "protein bar (20g protein)" }],
    steps: ["Unwrap. Eat. Done."],
  },
  {
    id: "snack-edamame-sea-salt",
    title: "Steamed Edamame with Sea Salt",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 5,
    prepTime: 1,
    servings: 1,
    macros: { calories: 190, protein: 17, carbs: 14, fat: 8 },
    tags: ["high-protein", "vegan", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "frozen edamame in pods" },
      { amount: "½ tsp", item: "flaky sea salt" },
    ],
    steps: ["Microwave or steam edamame 3–5 min.", "Toss with sea salt."],
  },
  {
    id: "snack-cherry-tomatoes-mozzarella",
    title: "Mozzarella & Cherry Tomato Skewers",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    macros: { calories: 200, protein: 13, carbs: 6, fat: 14 },
    tags: ["low-carb", "vegetarian", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "4 oz", item: "mozzarella pearls", perishable: true, shelfDays: 7 },
      { amount: "½ cup", item: "cherry tomatoes", perishable: true, shelfDays: 5 },
      { amount: "1 tsp", item: "balsamic glaze" },
      { amount: "4", item: "fresh basil leaves", perishable: true, shelfDays: 4 },
    ],
    steps: ["Thread or toss mozzarella, tomatoes, and basil.", "Drizzle with balsamic glaze."],
  },
  {
    id: "snack-overnight-oats-cup",
    title: "Mini Overnight Oats Cup",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 3,
    servings: 1,
    macros: { calories: 240, protein: 10, carbs: 38, fat: 6 },
    tags: ["high-carb", "low-fat", "meal-prep", "no-cook", "vegetarian"],
    source: "seed",
    ingredients: [
      { amount: "⅓ cup", item: "rolled oats" },
      { amount: "½ cup", item: "milk", perishable: true, shelfDays: 7 },
      { amount: "1 tsp", item: "honey" },
      { amount: "¼ cup", item: "berries", perishable: true, shelfDays: 4 },
    ],
    steps: ["Stir oats, milk, and honey in a small jar; refrigerate overnight.", "Top with berries."],
  },
  {
    id: "snack-banana-almond-butter",
    title: "Banana with Almond Butter",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 2,
    servings: 1,
    macros: { calories: 260, protein: 6, carbs: 33, fat: 13 },
    tags: ["balanced", "no-cook", "quick", "vegan", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1", item: "banana" },
      { amount: "1½ tbsp", item: "almond butter" },
    ],
    steps: ["Peel, dip, repeat."],
  },
  {
    id: "snack-chocolate-protein-pudding",
    title: "Chocolate Protein Pudding",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 4,
    servings: 1,
    macros: { calories: 200, protein: 28, carbs: 14, fat: 4 },
    tags: ["high-protein", "low-fat", "no-cook", "quick", "sweet", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "nonfat Greek yogurt", perishable: true, shelfDays: 10 },
      { amount: "1 scoop", item: "chocolate protein powder" },
      { amount: "1 tsp", item: "cocoa powder" },
    ],
    steps: ["Stir protein powder and cocoa into yogurt until pudding-thick."],
  },
  {
    id: "snack-avocado-toast-mini",
    title: "Mini Avocado Toast",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 3,
    prepTime: 4,
    servings: 1,
    macros: { calories: 230, protein: 6, carbs: 22, fat: 14 },
    tags: ["high-fat", "vegan", "quick"],
    source: "seed",
    ingredients: [
      { amount: "1 slice", item: "whole grain bread" },
      { amount: "½", item: "avocado", perishable: true, shelfDays: 3 },
      { amount: "1 pinch", item: "red pepper flakes" },
      { amount: "1 pinch", item: "flaky sea salt" },
    ],
    steps: ["Toast bread; smash avocado on top.", "Season with salt and pepper flakes."],
  },
  {
    id: "snack-deli-rollups",
    title: "Turkey & Cheese Roll-Ups",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 4,
    servings: 1,
    macros: { calories: 190, protein: 24, carbs: 3, fat: 9 },
    tags: ["high-protein", "low-carb", "keto", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "4 oz", item: "sliced turkey breast", perishable: true, shelfDays: 5 },
      { amount: "2 slices", item: "provolone, halved", perishable: true, shelfDays: 14 },
      { amount: "1 tsp", item: "Dijon mustard" },
    ],
    steps: ["Smear turkey slices with Dijon, lay cheese on top, and roll into pinwheels."],
  },
  {
    id: "snack-chia-pudding-cup",
    title: "Vanilla Chia Pudding Cup",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 3,
    servings: 1,
    macros: { calories: 220, protein: 7, carbs: 20, fat: 13 },
    tags: ["vegan", "meal-prep", "no-cook", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "2 tbsp", item: "chia seeds" },
      { amount: "¾ cup", item: "almond milk" },
      { amount: "1 tsp", item: "maple syrup" },
      { amount: "¼ tsp", item: "vanilla extract" },
    ],
    steps: ["Stir everything in a jar; refrigerate 4+ hours.", "Stir once more before eating."],
  },
  {
    id: "snack-popcorn-nutritional-yeast",
    title: "Popcorn with Nutritional Yeast",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 4,
    prepTime: 1,
    servings: 1,
    macros: { calories: 160, protein: 6, carbs: 26, fat: 5 },
    tags: ["high-carb", "low-fat", "vegan", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "3 tbsp", item: "popcorn kernels" },
      { amount: "1 tbsp", item: "nutritional yeast" },
      { amount: "1 tsp", item: "olive oil" },
    ],
    steps: ["Pop kernels (air popper or covered pot).", "Toss with oil and nutritional yeast."],
  },
  {
    id: "snack-smoked-salmon-cucumber",
    title: "Smoked Salmon Cucumber Bites",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    macros: { calories: 150, protein: 16, carbs: 5, fat: 8 },
    tags: ["high-protein", "low-carb", "keto", "no-cook", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "3 oz", item: "smoked salmon", perishable: true, shelfDays: 5 },
      { amount: "½", item: "cucumber, sliced into rounds", perishable: true, shelfDays: 7 },
      { amount: "2 tbsp", item: "whipped cream cheese", perishable: true, shelfDays: 14 },
    ],
    steps: ["Dab cream cheese on cucumber rounds; drape with salmon."],
  },
  {
    id: "snack-frozen-grapes-cheese",
    title: "Frozen Grapes & Cheddar Cubes",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 2,
    servings: 1,
    macros: { calories: 210, protein: 8, carbs: 24, fat: 10 },
    tags: ["balanced", "no-cook", "quick", "vegetarian", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "grapes, frozen", perishable: true, shelfDays: 7 },
      { amount: "1 oz", item: "sharp cheddar, cubed", perishable: true, shelfDays: 14 },
    ],
    steps: ["Keep grapes in the freezer; pair with cheddar straight from the fridge."],
  },
  {
    id: "snack-pretzels-mustard",
    title: "Pretzels with Honey Mustard",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 1,
    servings: 1,
    macros: { calories: 220, protein: 5, carbs: 44, fat: 3 },
    tags: ["high-carb", "low-fat", "no-cook", "quick", "vegan"],
    source: "seed",
    ingredients: [
      { amount: "2 oz", item: "pretzel twists" },
      { amount: "2 tbsp", item: "honey mustard" },
    ],
    steps: ["Dip pretzels in honey mustard."],
  },
  {
    id: "snack-pb-celery-raisins",
    title: "Ants on a Log",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 4,
    servings: 1,
    macros: { calories: 220, protein: 7, carbs: 20, fat: 14 },
    tags: ["balanced", "no-cook", "quick", "vegetarian", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "3 stalks", item: "celery", perishable: true, shelfDays: 14 },
      { amount: "2 tbsp", item: "peanut butter" },
      { amount: "1 tbsp", item: "raisins" },
    ],
    steps: ["Fill celery with peanut butter; dot with raisins."],
  },
  {
    id: "snack-clementine-pistachios",
    title: "Clementines & Pistachios",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 3,
    servings: 1,
    macros: { calories: 230, protein: 7, carbs: 26, fat: 12 },
    tags: ["balanced", "no-cook", "quick", "vegan", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "2", item: "clementines", perishable: true, shelfDays: 14 },
      { amount: "¼ cup", item: "pistachios, in shell" },
    ],
    steps: ["Peel, crack, snack."],
  },
  {
    id: "snack-mango-lassi",
    title: "Mango Lassi",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 4,
    servings: 1,
    macros: { calories: 240, protein: 12, carbs: 42, fat: 3 },
    tags: ["high-carb", "low-fat", "no-cook", "quick", "vegetarian", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "¾ cup", item: "frozen mango chunks" },
      { amount: "¾ cup", item: "nonfat Greek yogurt", perishable: true, shelfDays: 10 },
      { amount: "½ cup", item: "milk", perishable: true, shelfDays: 7 },
      { amount: "1 tsp", item: "honey" },
      { amount: "1 pinch", item: "ground cardamom" },
    ],
    steps: ["Blend everything until smooth and frothy."],
  },
  {
    id: "snack-roasted-chickpeas",
    title: "Crispy Roasted Chickpeas",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 30,
    prepTime: 5,
    servings: 2,
    macros: { calories: 180, protein: 9, carbs: 26, fat: 5 },
    tags: ["vegan", "high-carb", "low-fat", "meal-prep", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 can (15 oz)", item: "chickpeas, drained and dried" },
      { amount: "1 tbsp", item: "olive oil" },
      { amount: "1 tsp", item: "smoked paprika" },
      { amount: "½ tsp", item: "garlic powder" },
    ],
    steps: [
      "Toss dry chickpeas with oil and spices.",
      "Roast at 400°F for 25–30 min, shaking once, until crunchy.",
    ],
  },
  {
    id: "snack-caprese-toast-bite",
    title: "Ricotta & Berry Toast",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 3,
    prepTime: 3,
    servings: 1,
    macros: { calories: 240, protein: 11, carbs: 30, fat: 9 },
    tags: ["vegetarian", "quick", "sweet"],
    source: "seed",
    ingredients: [
      { amount: "1 slice", item: "whole grain bread" },
      { amount: "⅓ cup", item: "ricotta", perishable: true, shelfDays: 7 },
      { amount: "¼ cup", item: "berries", perishable: true, shelfDays: 4 },
      { amount: "1 tsp", item: "honey" },
    ],
    steps: ["Toast bread; spread ricotta.", "Top with berries and a drizzle of honey."],
  },
  {
    id: "snack-guac-single-chips",
    title: "Single-Serve Guacamole & Chips",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    macros: { calories: 290, protein: 4, carbs: 28, fat: 19 },
    tags: ["high-fat", "vegan", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "½", item: "avocado", perishable: true, shelfDays: 3 },
      { amount: "1 tbsp", item: "pico de gallo", perishable: true, shelfDays: 4 },
      { amount: "½", item: "lime", perishable: true, shelfDays: 14 },
      { amount: "1 oz", item: "tortilla chips" },
    ],
    steps: ["Mash avocado with pico and lime juice.", "Scoop with chips."],
  },
  {
    id: "snack-matcha-latte-protein",
    title: "Iced Protein Matcha Latte",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 3,
    servings: 1,
    macros: { calories: 160, protein: 26, carbs: 9, fat: 3 },
    tags: ["high-protein", "low-carb", "low-fat", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 tsp", item: "matcha powder" },
      { amount: "1 scoop", item: "vanilla protein powder" },
      { amount: "1 cup", item: "unsweetened almond milk" },
      { amount: "1 cup", item: "ice" },
    ],
    steps: ["Shake matcha, protein powder, and almond milk hard.", "Pour over ice."],
  },
  {
    id: "snack-date-walnut-bites",
    title: "Stuffed Dates with Walnuts",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 4,
    servings: 1,
    macros: { calories: 250, protein: 4, carbs: 38, fat: 11 },
    tags: ["high-carb", "vegan", "no-cook", "quick", "sweet", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "4", item: "Medjool dates, pitted" },
      { amount: "8 halves", item: "walnuts" },
      { amount: "1 pinch", item: "flaky sea salt" },
    ],
    steps: ["Stuff each date with two walnut halves.", "Finish with a tiny pinch of salt."],
  },
  {
    id: "snack-kefir-berry-glass",
    title: "Kefir & Berry Glass",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 2,
    servings: 1,
    macros: { calories: 170, protein: 11, carbs: 24, fat: 4 },
    tags: ["low-fat", "no-cook", "quick", "vegetarian", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "plain kefir", perishable: true, shelfDays: 10 },
      { amount: "½ cup", item: "mixed berries", perishable: true, shelfDays: 4 },
    ],
    steps: ["Pour kefir over berries. Eat with a spoon or drink it."],
  },
  {
    id: "snack-pb-protein-energy-balls",
    title: "Peanut Butter Protein Energy Balls",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 12,
    servings: 4,
    macros: { calories: 230, protein: 12, carbs: 22, fat: 11 },
    tags: ["high-protein", "meal-prep", "no-cook", "vegetarian"],
    source: "seed",
    ingredients: [
      { amount: "1 cup", item: "rolled oats" },
      { amount: "½ cup", item: "peanut butter" },
      { amount: "1 scoop", item: "vanilla protein powder" },
      { amount: "2 tbsp", item: "honey" },
      { amount: "2 tbsp", item: "mini chocolate chips" },
    ],
    steps: [
      "Mix everything into a stiff dough (add a splash of water if dry).",
      "Roll into 12 balls. Refrigerate — 3 per serving, keeps a week.",
    ],
  },
  {
    id: "snack-seaweed-avocado-rice",
    title: "Seaweed Snack & Avocado Rice Bites",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 6,
    servings: 1,
    macros: { calories: 240, protein: 5, carbs: 34, fat: 10 },
    tags: ["vegan", "high-carb", "no-cook", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 pack", item: "roasted seaweed snacks" },
      { amount: "½ cup", item: "cooked rice (leftover is fine)" },
      { amount: "¼", item: "avocado, sliced", perishable: true, shelfDays: 3 },
      { amount: "1 tsp", item: "soy sauce (low sodium)" },
    ],
    steps: ["Spoon rice and avocado onto seaweed sheets.", "Dot with soy sauce; fold like tiny tacos."],
  },
  {
    id: "snack-cucumber-tajin",
    title: "Cucumber & Mango with Tajín",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 5,
    servings: 1,
    macros: { calories: 120, protein: 2, carbs: 28, fat: 1 },
    tags: ["vegan", "low-fat", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "½", item: "cucumber, in spears", perishable: true, shelfDays: 7 },
      { amount: "½ cup", item: "mango chunks", perishable: true, shelfDays: 4 },
      { amount: "1 tsp", item: "Tajín seasoning" },
      { amount: "½", item: "lime", perishable: true, shelfDays: 14 },
    ],
    steps: ["Arrange cucumber and mango.", "Squeeze lime over and dust generously with Tajín."],
  },
  {
    id: "snack-dark-chocolate-almonds",
    title: "Dark Chocolate & Almonds",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 1,
    servings: 1,
    macros: { calories: 260, protein: 7, carbs: 18, fat: 19 },
    tags: ["high-fat", "no-cook", "quick", "sweet", "vegan", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 oz", item: "dark chocolate (70%+)" },
      { amount: "¼ cup", item: "raw almonds" },
    ],
    steps: ["Alternate bites. Savor it."],
  },
  {
    id: "snack-caesar-snap-peas",
    title: "Snap Peas with Caesar Dip",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 3,
    servings: 1,
    macros: { calories: 140, protein: 9, carbs: 12, fat: 7 },
    tags: ["low-carb", "low-fat", "no-cook", "quick", "vegetarian", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1½ cups", item: "sugar snap peas", perishable: true, shelfDays: 5 },
      { amount: "3 tbsp", item: "Greek yogurt Caesar dressing", perishable: true, shelfDays: 14 },
    ],
    steps: ["Wash, dip, crunch."],
  },
  {
    id: "snack-casein-night-pudding",
    title: "Bedtime Casein Pudding",
    cuisine: "Snack",
    mealType: ["snack"],
    cookTime: 0,
    prepTime: 3,
    servings: 1,
    macros: { calories: 180, protein: 27, carbs: 10, fat: 4 },
    tags: ["high-protein", "low-carb", "no-cook", "quick", "gluten-free"],
    source: "seed",
    ingredients: [
      { amount: "1 scoop", item: "casein protein powder" },
      { amount: "½ cup", item: "milk", perishable: true, shelfDays: 7 },
      { amount: "1 tbsp", item: "Greek yogurt", perishable: true, shelfDays: 10 },
    ],
    steps: ["Whisk casein into milk and yogurt until pudding-thick. Slow-digesting protein for overnight."],
  },
];
